# -*- coding: utf-8 -*-
"""Speed_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COwvPmshJCpru2AkRJ2iaqcN4HE2F-Ae
"""

#определяет смазанность машины или объекта вокруг нее?


import numpy as np
import cv2
import os
import time

try:
    import torch
except Exception:
    torch = None
from PIL import Image
from PIL.ExifTags import TAGS
import matplotlib.pyplot as plt
from ultralytics import YOLO
from google.colab import files

# классы машин COCO: car, motorcycle, bus, truck
CAR_CLASSES = {2, 3, 5, 7}

# -----------------------------
# НАСТРОЙКИ (все ключевые параметры — здесь)
# -----------------------------
CFG = {
    # Детекция/сегментация
    "model_name": "yolov8n-seg.pt",
    "det_conf": 0.25,
    "merge_iou": 0.30,          # объединять маски/боксы одной машины, если пересекаются (IoU)
    "mask_dilate_frac": 0.004,  # расширение маски (доля от min(H,W)), чтобы "захватить всю машину"
    "crop_pad_frac": 0.10,      # расширение ROI вокруг машины

    # Поиск направления смаза
    "theta_coarse_step": 5.0,
    "theta_fine_step": 1.0,
    "theta_fine_window": 12.0,  # +/- градусов вокруг лучшего coarse
    "theta_search_min": -90.0,
    "theta_search_max": 90.0,
    "exposure_range_s": (1/2000, 1/30),
    "min_vehicle_area_frac": 0.003,
    "lane_dash_len_m": 3.0,
    "blur_conf_floor": 0.10,
    "blur_conf_pow": 1.0,
    "prefer_lane_scale": True,
    "lane_vs_vehicle_alpha": 0.7,



    # Оценка длины смаза K
    "edge_thr_k_mad": 3.0,      # порог = median + k*MAD по |SobelX| внутри маски
    "edge_win_frac": 0.25,      # окно около границы объекта (доля ширины объекта)
    "min_row_coverage": 0.30,   # минимальная доля маски в строке, чтобы строка учитывалась
    "k_iter_max": 20,
    "k_converge_eps": 1.0,
    "k_keep_ratio": 0.75,       # как в статье: сохраняем строки, где сумма ширин > 0.75*(2*K)

        # Скорость без z/f/sensor: берём типовую длину ТС и его размер в пикселях вдоль смаза
    "default_exposure_s": 0.008,   # если EXIF ExposureTime отсутствует
    "vehicle_length_m_by_cls": {   # типовая длина (метры)
        2: 4.5,    # car
        3: 2.1,    # motorcycle
        5: 12.0,   # bus
        7: 8.0     # truck
    },
    "default_vehicle_length_m": 4.5,


    # Вывод/визуализация
    "show_debug": True,
}

# -----------------------------
# ВСПОМОГАТЕЛЬНЫЕ
# -----------------------------
def _exif_to_float(v):
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, tuple) and len(v) == 2:
        num, den = v
        den = float(den)
        if den != 0:
            return float(num) / den
        return None
    try:
        return float(v)
    except Exception:
        return None

def read_exif(pil_img):
    exif = {}
    try:
        raw = pil_img.getexif()
        for tag_id, value in raw.items():
            tag = TAGS.get(tag_id, tag_id)
            exif[tag] = value
    except Exception:
        pass

    out = {
        "ExposureTime_s": None,
        "FocalLength_mm": None,
        "Make": None,
        "Model": None
    }

    out["ExposureTime_s"] = _exif_to_float(exif.get("ExposureTime"))
    out["FocalLength_mm"]  = _exif_to_float(exif.get("FocalLength"))
    out["Make"]  = exif.get("Make")
    out["Model"] = exif.get("Model")
    return out

def load_image_from_upload():
    uploaded = files.upload()
    fname = next(iter(uploaded.keys()))
    pil = Image.open(fname).convert("RGB")
    exif = read_exif(pil)
    img_np = np.array(pil)
    img_bgr = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    return fname, pil, img_bgr, exif

def bbox_iou(a, b):
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b
    ix1 = max(ax1, bx1)
    iy1 = max(ay1, by1)
    ix2 = min(ax2, bx2)
    iy2 = min(ay2, by2)
    iw = max(0.0, ix2 - ix1)
    ih = max(0.0, iy2 - iy1)
    inter = iw * ih
    if inter <= 0:
        return 0.0
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - inter
    if union <= 0:
        return 0.0
    return inter / union

def rotate_image_and_mask(img, mask, angle_deg):
    h, w = img.shape[:2]
    cx, cy = w * 0.5, h * 0.5
    M = cv2.getRotationMatrix2D((cx, cy), angle_deg, 1.0)

    img_rot = cv2.warpAffine(img, M, (w, h), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(0, 0, 0))
    mask_rot = cv2.warpAffine(mask, M, (w, h), flags=cv2.INTER_NEAREST, borderMode=cv2.BORDER_CONSTANT, borderValue=0)

    return img_rot, mask_rot, M
def mask_span_x(mask):
    ys, xs = np.where(mask > 0)
    if xs.size == 0:
        return None
    return float(xs.max() - xs.min() + 1)


def robust_thr_from_mad(values, k):
    values = values[np.isfinite(values)]
    if values.size == 0:
        return None
    med = np.median(values)
    mad = np.median(np.abs(values - med))
    return float(med + k * (mad + 1e-9))

def mode_int(arr):
    arr = np.asarray(arr, dtype=np.int32)
    arr = arr[arr > 0]
    if arr.size == 0:
        return None
    mx = int(arr.max())
    bc = np.bincount(arr, minlength=mx + 1)
    return int(bc.argmax())

def comp_len_near_boundary(edge_row_bool, x_boundary, x0, x1):
    seg = edge_row_bool[x0:x1]
    if seg.size == 0 or not np.any(seg):
        return 0

    idx = np.flatnonzero(seg)
    splits = np.where(np.diff(idx) > 1)[0]
    starts = np.r_[0, splits + 1]
    ends   = np.r_[splits, idx.size - 1]

    best_len = 0
    best_dist = None
    xb = x_boundary - x0

    for s, e in zip(starts, ends):
        run = idx[s:e+1]
        run_len = int(run.size)
        run_center = float(np.mean(run))
        dist = abs(run_center - xb)
        if best_dist is None or dist < best_dist:
            best_dist = dist
            best_len = run_len

    return best_len

# -----------------------------
# 1) СЕГМЕНТАЦИЯ МАШИНЫ (полностью, маской)
# -----------------------------
def detect_vehicle_mask(img_bgr, cfg):
    # Возвращает СПИСОК объектов:
    # [{"mask":mask_uint8(H,W), "bbox":[x1,y1,x2,y2], "cls":cls_id, "conf":conf, "area":area_px}, ...]
    model_path = str(cfg.get("yolo_model_path") or cfg.get("model_name") or "").strip().strip('"').strip("'")
    if not model_path:
        raise RuntimeError("yolo_model_path/model_name не задан.")

    yolo_dir = str(cfg.get("yolo_dir", "") or "").strip().strip('"').strip("'")
    if yolo_dir and (not os.path.isabs(model_path)):
        model_path = os.path.join(yolo_dir, model_path)

    model_path = os.path.abspath(os.path.expandvars(os.path.expanduser(model_path)))
    if not os.path.exists(model_path):
        raise RuntimeError(f"Файл модели YOLO не найден: {model_path}")

    model = YOLO(model_path)
    H, W = img_bgr.shape[:2]

    res = model.predict(
        img_bgr,
        conf=cfg["det_conf"],
        imgsz=cfg.get("imgsz", 640),
        verbose=False
    )[0]

    if res.boxes is None or len(res.boxes) == 0:
        return []

    boxes = res.boxes.xyxy.cpu().numpy().astype(np.float32)
    confs = res.boxes.conf.cpu().numpy().astype(np.float32)
    clss  = res.boxes.cls.cpu().numpy().astype(np.int32)

    keep = [i for i, c in enumerate(clss) if int(c) in CAR_CLASSES]
    if not keep:
        return []

    masks_data = None
    masks_xy = None
    if res.masks is not None:
        if hasattr(res.masks, "data") and res.masks.data is not None:
            masks_data = res.masks.data.cpu().numpy()  # (N, h, w) в размере модели
        if hasattr(res.masks, "xy") and res.masks.xy is not None:
            masks_xy = res.masks.xy

    dets = []
    for i in keep:
        x1, y1, x2, y2 = boxes[i].tolist()
        x1 = float(max(0, min(W - 1, x1)))
        y1 = float(max(0, min(H - 1, y1)))
        x2 = float(max(0, min(W - 1, x2)))
        y2 = float(max(0, min(H - 1, y2)))
        dets.append({
            "i": int(i),
            "cls": int(clss[i]),
            "conf": float(confs[i]),
            "box": [x1, y1, x2, y2]
        })

    if not dets:
        return []

    # --- группировка пересекающихся боксов (склейка частей одной машины) ---
    n = len(dets)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for a in range(n):
        for b in range(a + 1, n):
            if dets[a]["cls"] != dets[b]["cls"]:
                continue
            if bbox_iou(dets[a]["box"], dets[b]["box"]) >= cfg["merge_iou"]:
                union(a, b)

    groups = {}
    for idx in range(n):
        root = find(idx)
        groups.setdefault(root, []).append(idx)

    # --- параметры постобработки маски ---
    min_area = float(cfg.get("min_vehicle_area_frac", 0.0)) * float(H * W)

    k = max(3, int(round(min(H, W) * cfg["mask_dilate_frac"])))
    if k % 2 == 0:
        k += 1
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))
    close_iter = int(cfg.get("mask_close_iter", 1))

    out = []

    for comp in groups.values():
        cls_id = dets[comp[0]]["cls"]
        conf = max(dets[j]["conf"] for j in comp)

        mask = np.zeros((H, W), dtype=np.uint8)

        if masks_data is not None:
            # ВАЖНО: masks_data[ii] почти всегда НЕ (H,W) -> приводим к (H,W)
            for j in comp:
                ii = dets[j]["i"]
                m = masks_data[ii]  # (h,w) float/0..1

                if (m.shape[0] != H) or (m.shape[1] != W):
                    m = cv2.resize(m.astype(np.float32), (W, H), interpolation=cv2.INTER_NEAREST)

                m = (m > 0.5).astype(np.uint8)
                mask = np.maximum(mask, m * 255)

        elif masks_xy is not None:
            for j in comp:
                ii = dets[j]["i"]
                poly = masks_xy[ii]
                if poly is None:
                    continue
                if isinstance(poly, np.ndarray):
                    poly = [poly]
                for pts in poly:
                    pts_i = np.round(pts).astype(np.int32)
                    if pts_i.size >= 6:
                        cv2.fillPoly(mask, [pts_i], 255)

        else:
            for j in comp:
                x1, y1, x2, y2 = dets[j]["box"]
                x1 = int(max(0, min(W - 1, x1)))
                y1 = int(max(0, min(H - 1, y1)))
                x2 = int(max(0, min(W - 1, x2)))
                y2 = int(max(0, min(H - 1, y2)))
                mask[y1:y2, x1:x2] = 255

        if np.count_nonzero(mask) == 0:
            continue

        # Доработка маски, чтобы захватывало всю машину
        mask = cv2.dilate(mask, kernel, iterations=1)
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=close_iter)

        area = int(np.count_nonzero(mask))
        if area < min_area:
            continue

        ys, xs = np.where(mask > 0)
        x1 = int(xs.min()); y1 = int(ys.min())
        x2 = int(xs.max()); y2 = int(ys.max())

        out.append({
            "mask": mask,
            "bbox": [x1, y1, x2, y2],
            "cls": cls_id,
            "conf": float(conf),
            "area": area
        })

    out.sort(key=lambda d: d["area"], reverse=True)
    return out


# -----------------------------
# 2) ОЦЕНКА НАПРАВЛЕНИЯ СМАЗА (theta)
#    Идея: направление, где модуль направленной производной минимален
# -----------------------------
def estimate_motion_direction(gray, mask, cfg):
    gray_f = gray.astype(np.float32)
    gx = cv2.Sobel(gray_f, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(gray_f, cv2.CV_32F, 0, 1, ksize=3)

    m = (mask > 0)
    if np.count_nonzero(m) == 0:
        return None

    def energy(theta_deg):
        t = np.deg2rad(theta_deg)
        d = gx * np.cos(t) + gy * np.sin(t)
        return float(np.mean(np.abs(d[m])))

    thetas_coarse = np.arange(cfg["theta_search_min"], cfg["theta_search_max"] + 1e-9, cfg["theta_coarse_step"], dtype=np.float32)
    e_coarse = [(th, energy(float(th))) for th in thetas_coarse]
    best_th, best_e = min(e_coarse, key=lambda x: x[1])

    w = float(cfg["theta_fine_window"])
    thetas_fine = np.arange(best_th - w, best_th + w + 1e-9, cfg["theta_fine_step"], dtype=np.float32)
    thetas_fine = thetas_fine[(thetas_fine >= cfg["theta_search_min"]) & (thetas_fine <= cfg["theta_search_max"])]

    e_fine = [(th, energy(float(th))) for th in thetas_fine]
    best_th2, best_e2 = min(e_fine, key=lambda x: x[1])

    return float(best_th2)

# -----------------------------
# 3) ОЦЕНКА ДЛИНЫ СМАЗА K (в пикселях) по размытым границам
#    Реализация по схеме из статьи: по строкам, мода ширин, итеративное уточнение
# -----------------------------


def estimate_blur_length_k(gray, mask, cfg):
    gray_f = gray.astype(np.float32)
    sobx = cv2.Sobel(gray_f, cv2.CV_32F, 1, 0, ksize=3)
    edge = np.abs(sobx)

    m = (mask > 0)
    if np.count_nonzero(m) == 0:
        return None, None

    thr = robust_thr_from_mad(edge[m], cfg["edge_thr_k_mad"])
    if thr is None:
        return None, None

    H, W = gray.shape[:2]
    rows_sums = []

    for y in range(H):
        xs = np.flatnonzero(mask[y] > 0)
        if xs.size == 0:
            continue

        xL = int(xs.min())
        xR = int(xs.max())
        obj_w = max(1, xR - xL + 1)

        if xs.size < int(round(cfg["min_row_coverage"] * obj_w)):
            continue

        win = int(round(cfg["edge_win_frac"] * obj_w))
        win = max(3, win)

        x0L = max(0, xL - win)
        x1L = min(W, xL + win + 1)

        x0R = max(0, xR - win)
        x1R = min(W, xR + win + 1)

        row_bool = (edge[y] > thr)

        wL = comp_len_near_boundary(row_bool, xL, x0L, x1L)
        wR = comp_len_near_boundary(row_bool, xR, x0R, x1R)

        s = int(wL + wR)
        if s > 0:
            rows_sums.append(s)

    rows_sums = np.asarray(rows_sums, dtype=np.int32)
    if rows_sums.size == 0:
        return None, None

    s_mode = mode_int(rows_sums)
    if s_mode is None or s_mode <= 0:
        return None, None

    K = 0.5 * float(s_mode)

    hist_trace = [(float(K), int(s_mode), int(rows_sums.size))]

    for _ in range(int(cfg["k_iter_max"])):
        keep_thr = cfg["k_keep_ratio"] * (2.0 * K)
        kept = rows_sums[rows_sums >= keep_thr]

        if kept.size == 0:
            break

        s_mode2 = mode_int(kept)
        if s_mode2 is None or s_mode2 <= 0:
            break

        K2 = 0.5 * float(s_mode2)
        hist_trace.append((float(K2), int(s_mode2), int(kept.size)))

        if abs(K2 - K) <= float(cfg["k_converge_eps"]):
            K = K2
            break

        K = K2

    return float(K), {
        "thr": float(thr),
        "rows_used": int(rows_sums.size),
        "trace": hist_trace
    }

def blur_confidence(gray_rot, mask_rot, theta_deg, K_px):
    # Быстрая проверка: если K маленький или контраст вдоль направления смаза не падает — считаем, что смаза нет.
    if K_px is None or K_px < 3.0:
        return 0.0

    g = gray_rot.astype(np.float32)
    gx = cv2.Sobel(g, cv2.CV_32F, 1, 0, ksize=3)
    gy = cv2.Sobel(g, cv2.CV_32F, 0, 1, ksize=3)

    m = (mask_rot > 0)
    if np.count_nonzero(m) == 0:
        return 0.0

    t = np.deg2rad(theta_deg)
    # производная вдоль смаза (после поворота смаз примерно по X -> t около 0, но оставим универсально)
    d_along = gx * np.cos(t) + gy * np.sin(t)
    d_perp  = -gx * np.sin(t) + gy * np.cos(t)

    a = float(np.mean(np.abs(d_along[m])))
    p = float(np.mean(np.abs(d_perp[m])))

    if p <= 1e-6:
        return 0.0

    # при реальном смазе вдоль смаза градиент меньше, чем поперёк
    ratio = a / p  # меньше => лучше
    conf = max(0.0, min(1.0, (0.9 - ratio) / 0.9))  # ratio<=0.0..0.9 -> 1..0
    return float(conf)

# -----------------------------
# 4) СКОРОСТЬ по формуле v = z * K * sx / (T * f)
#    (как в статье) — нужны z, T, f и sx (или sensor_width)
# -----------------------------
def compute_speed_kmh(
    K_px,
    z_m=None,
    T_s=None,
    focal_mm=None,
    sensor_width_mm=None,
    pixel_size_um=None,
    image_width_px=None,
    *,
    obj_span_px=None,
    cls_id=None,
    cfg=None
):
    # K_px — длина смаза в пикселях (в уже повернутом ROI, где смаз горизонтальный)

    if K_px is None or K_px <= 0:
        return None

    # Режим А (старый): если вдруг есть все параметры — считаем по оптике
    have_optical = (
        (z_m is not None) and (T_s is not None) and (focal_mm is not None) and
        (
            (pixel_size_um is not None and pixel_size_um > 0) or
            (sensor_width_mm is not None and sensor_width_mm > 0 and image_width_px is not None and image_width_px > 0)
        )
    )
    if have_optical:
        if pixel_size_um is not None and pixel_size_um > 0:
            sx_m = (pixel_size_um * 1e-6)
        else:
            sx_m = (sensor_width_mm * 1e-3) / float(image_width_px)

        f_m = (focal_mm * 1e-3)
        v_m_s = float(z_m) * float(K_px) * float(sx_m) / (float(T_s) * float(f_m))
        return float(v_m_s * 3.6)

    # Режим B (новый): без z/f/sensor — по типовой длине ТС и его размеру в пикселях вдоль смаза
    if cfg is None:
        return None

    if T_s is None or T_s <= 0:
        T_s = cfg.get("default_exposure_s")
    if T_s is None or T_s <= 0:
        return None

    if obj_span_px is None or obj_span_px <= 0:
        return None

    lengths = cfg.get("vehicle_length_m_by_cls", {})
    default_len = cfg.get("default_vehicle_length_m")

    L_m = None
    if cls_id is not None:
        L_m = lengths.get(int(cls_id))
    if L_m is None:
        L_m = default_len

    if L_m is None or L_m <= 0:
        return None

    # meters_per_pixel = L_m / obj_span_px
    # v = (K_px * meters_per_pixel) / T_s
    v_m_s = (float(K_px) * (float(L_m) / float(obj_span_px))) / float(T_s)
    return float(v_m_s * 3.6)


# -----------------------------
# 5) ВИЗУАЛИЗАЦИЯ
# -----------------------------
def draw_results_multi(img_bgr, results):
    vis = img_bgr.copy()
    H, W = vis.shape[:2]

    for r in results:
        x1, y1, x2, y2 = r["bbox"]
        cv2.rectangle(vis, (x1, y1), (x2, y2), (0, 255, 0), 2)

        cx = int((x1 + x2) * 0.5)
        cy = int((y1 + y2) * 0.5)

        theta = r["theta"]
        if theta is not None:
            L = int(round(0.25 * max(1, (x2 - x1 + 1))))
            ang = np.deg2rad(theta)
            dx = int(round(L * np.cos(ang)))
            dy = int(round(L * np.sin(ang)))
            p1 = (cx - dx, cy - dy)
            p2 = (cx + dx, cy + dy)
            cv2.arrowedLine(vis, p1, p2, (0, 0, 255), 2, tipLength=0.2)

        K_px = r["K"]
        sp = r["speed"]

        lines = [f"#{r['idx']} K={None if K_px is None else round(K_px,1)}px"]
        if sp is not None:
            lines.append(f"v={round(sp,1)} km/h")


        ty = max(15, y1 - 5)
        for i, t in enumerate(lines):
            ytxt = ty + 18*i
            cv2.putText(vis, t, (x1, ytxt), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 3, lineType=cv2.LINE_AA)
            cv2.putText(vis, t, (x1, ytxt), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 1, lineType=cv2.LINE_AA)

    rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(14, 8))
    plt.imshow(rgb)
    plt.axis("off")
    plt.show()


# -----------------------------
# 6) ГЛАВНЫЙ ЗАПУСК
# -----------------------------
def estimate_meters_per_pixel_from_lane_dashes(img_bgr, bbox, dash_len_m=3.0):
    # Простой оценщик масштаба: ищем жёлтые/оранжевые штрихи разметки и измеряем их длину в пикселях
    # dash_len_m — реальная длина штриха (обычно 3 м), можно поменять в CFG

    H, W = img_bgr.shape[:2]
    x1, y1, x2, y2 = bbox

    # ROI ниже машины (разметка обычно там)
    pad = int(0.5 * max(1, (y2 - y1 + 1)))
    ry1 = min(H - 1, y2)
    ry2 = min(H - 1, y2 + pad)
    rx1 = max(0, x1 - int(0.3 * (x2 - x1 + 1)))
    rx2 = min(W - 1, x2 + int(0.3 * (x2 - x1 + 1)))

    if ry2 <= ry1 or rx2 <= rx1:
        return None

    roi = img_bgr[ry1:ry2+1, rx1:rx2+1]
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

    # маска “жёлто-оранжевого”
    lower = np.array([10, 70, 70], dtype=np.uint8)
    upper = np.array([40, 255, 255], dtype=np.uint8)
    m = cv2.inRange(hsv, lower, upper)

    m = cv2.medianBlur(m, 5)
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((3,3), np.uint8), iterations=1)

    # контуры штрихов
    cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts:
        return None

    lengths_px = []
    for c in cnts:
        area = cv2.contourArea(c)
        if area < 40:
            continue
        rect = cv2.minAreaRect(c)
        (cx, cy), (rw, rh), ang = rect
        L = max(rw, rh)
        S = min(rw, rh)
        if S <= 1:
            continue
        # штрих — вытянутый прямоугольник
        if L / S < 3.0:
            continue
        lengths_px.append(float(L))

    if not lengths_px:
        return None

    dash_px = float(np.median(lengths_px))
    if dash_px <= 1:
        return None

    return float(dash_len_m / dash_px)


def process_image_speed_by_blur():
    fname, pil, img_bgr, exif = load_image_from_upload()
    H, W = img_bgr.shape[:2]

    print("Файл:", fname)
    print("Размер (W x H):", W, "x", H)
    print("EXIF ExposureTime (s):", exif.get("ExposureTime_s"))
    print("EXIF FocalLength (mm):", exif.get("FocalLength_mm"))

    vehicles = detect_vehicle_mask(img_bgr, CFG)
    if not vehicles:
        print("Машины не найдены.")
        return

    results = []

    for idx, v in enumerate(vehicles, start=1):
        mask_full = v["mask"]
        bbox = v["bbox"]
        cls_id = v["cls"]
        conf = v["conf"]

        x1, y1, x2, y2 = bbox

        roi_img = img_bgr[y1:y2+1, x1:x2+1].copy()
        roi_mask = mask_full[y1:y2+1, x1:x2+1].copy()

        gray = cv2.cvtColor(roi_img, cv2.COLOR_BGR2GRAY)

        theta = estimate_motion_direction(gray, roi_mask, CFG)
        if theta is None:
            continue

        roi_img_rot, roi_mask_rot, _ = rotate_image_and_mask(roi_img, roi_mask, -theta)
        gray_rot = cv2.cvtColor(roi_img_rot, cv2.COLOR_BGR2GRAY)

        K_px, k_dbg = estimate_blur_length_k(gray_rot, roi_mask_rot, CFG)
        # выдержка: EXIF -> иначе default
                # выдержка: EXIF -> иначе default
        T_s_used = exif.get("ExposureTime_s")
        if T_s_used is None:
            T_s_used = CFG["default_exposure_s"]

        # уверенность смаза (0..1) -> используем как вес, НЕ как запрет
        bc = blur_confidence(gray_rot, roi_mask_rot, 0.0, K_px)
        bc_floor = float(CFG["blur_conf_floor"])
        bc_pow = float(CFG["blur_conf_pow"])
        bc_w = max(bc_floor, float(bc)) ** bc_pow

        # 1) масштаб по разметке (если найден)
        m_per_px = estimate_meters_per_pixel_from_lane_dashes(
            img_bgr=img_bgr,
            bbox=bbox,
            dash_len_m=CFG["lane_dash_len_m"]
        )

        speed_lane = None
        if (m_per_px is not None) and (K_px is not None) and (float(K_px) > 0.0) and (float(T_s_used) > 0.0):
            v_m_s = (float(K_px) * float(m_per_px)) / float(T_s_used)
            speed_lane = float(v_m_s * 3.6) * bc_w

        # 2) масштаб по типовой длине авто (fallback, как раньше)
        span_px = mask_span_x(roi_mask_rot)
        speed_vehicle = compute_speed_kmh(
            K_px=K_px,
            T_s=T_s_used,
            cls_id=cls_id,
            obj_span_px=span_px,
            cfg=CFG
        )
        if speed_vehicle is not None:
            speed_vehicle = float(speed_vehicle) * bc_w

        # 3) итоговая скорость: если есть оба — смешиваем, иначе берём что есть
        speed_kmh = None
        if (speed_lane is not None) and (speed_vehicle is not None):
            alpha = float(CFG["lane_vs_vehicle_alpha"])
            speed_kmh = alpha * float(speed_lane) + (1.0 - alpha) * float(speed_vehicle)
        elif speed_lane is not None:
            speed_kmh = speed_lane
        elif speed_vehicle is not None:
            speed_kmh = speed_vehicle


        results.append({
            "idx": idx,
            "cls": cls_id,
            "conf": conf,
            "bbox": bbox,
            "theta": theta,
            "K": K_px,
            "T_s": T_s_used,
            "speed": speed_kmh,
        })

    if not results:
        print("Не удалось посчитать параметры ни для одной машины.")
        return

    # Печать результатов по всем
    for r in results:
        print(f"#{r['idx']} cls={r['cls']} conf={r['conf']:.3f} theta={r['theta']:.1f} K={None if r['K'] is None else round(r['K'],2)} T={r['T_s']}")

        if r["speed"] is None:
            print("  speed: None")
        else:
            print("  speed (km/h):", round(r["speed"], 2))

    # Отрисовка всех машин на одном изображении
    draw_results_multi(img_bgr, results)

# ---------
    # ВВОД ПАРАМЕТРОВ ДЛЯ СКОРОСТИ (обязательные для км/ч)
    # ---------
    # z_m            — расстояние до машины (метры)
    # T_s            — выдержка/экспозиция (секунды)
    # focal_mm       — фокусное (мм)
    # sensor_width_mm или pixel_size_um — одно из двух, чтобы получить sx (метры на пиксель)
    #
    # Если T_s / focal_mm есть в EXIF — можно оставить None и взять из EXIF.
    # ---------
    # ---------
    # СКОРОСТЬ БЕЗ z/f/sensor:
    # берём выдержку из EXIF, если нет — CFG["default_exposure_s"]
    # берём размер ТС в пикселях вдоль смаза (после поворота он по X)
    # берём типовую длину ТС по классу
    # ---------
# ЗАПУСК
process_image_speed_by_blur()

def run(image_path: str, out_dir: str, cfg: dict, device_mode: str = "auto") -> dict:
    """
    Должна вернуть dict в формате ModuleResult:
    {
      "module_id": "...",
      "image_w": int,
      "image_h": int,
      "device_used": "gpu|cpu",
      "warnings": [..],
      "annotated_image_path": "...",
      "cleaned_image_path": "...",
      "artifacts": {...},
      "timings_ms": {...},
      "detections": [ { "bbox_xyxy":[x1,y1,x2,y2], "conf":float, "cls_id":int, "cls_name":str, "meta":{} } ]
    }
    """
    raise NotImplementedError("Замените телo run() на вызов вашей логики внутри этого файла и сбор результата в dict ModuleResult")