# -*- coding: utf-8 -*-
"""Vehicle_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQ1g78TtC53VY8bK3YucEmCPLyXdocuu
"""


import os
import re
import sys
import json
import time
import shutil
import hashlib
import subprocess
from io import BytesIO
from datetime import datetime
from pathlib import Path

import cv2
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except Exception:
    pillow_heif = None

try:
    from huggingface_hub import hf_hub_download
except Exception:
    hf_hub_download = None

from pathlib import Path
from PIL import Image as PILImage, ImageOps
from ultralytics import YOLO

try:
    from google.colab import drive, files
except Exception:
    drive = None
    files = None

try:
    from IPython.display import display, Image as IPImage
except Exception:
    display = None
    IPImage = None


def log(msg: str):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")

CFG = {
    "DRONE": "/content/drive/MyDrive/DRONE",
    "DATA_SRC_REL": "images_for_training",

    "RUNS": "/content/runs",
    "DET_ROOT": "/content/data_det",
    "CLS_ROOT": "/content/data_cls",

    "MODEL_PATH": "/content/drive/MyDrive/DRONE/data_det/yolo11x-visdrone.pt",
    "KEEP_CLASS_NAMES": {"car", "van", "truck", "bus", "motorcycle"},

    "TILE": 640,
    "OVERLAP": 0.2,
    "AUTO_TILE_TARGET": 640,

    "BASE_IMGSZ": "auto",
    "TILED_IMGSZ": "auto",
    "TILED_BATCH": 16,

    "VAL_PCT": 15,

    "DET_CONF": 0.001,
    "DET_IOU": 0.9,
    "DET_MAX_DET": 3000,
    "DET_NMS_THR": 0.95,

    "MAX_CROPS_PER_IMAGE": None,

    "CLS_RUN_NAME": "verifier_car_bg",
    "CLS_IMGSZ": 128,
}

def pick_device(prefer_gpu: bool = True):
    if prefer_gpu:
        try:
            if torch.cuda.is_available():
                return 0
        except Exception:
            pass
    return "cpu"

PRED_DEVICE = pick_device(prefer_gpu=True)
CLS_DEVICE  = pick_device(prefer_gpu=True)

log(f"PRED_DEVICE={PRED_DEVICE}, CLS_DEVICE={CLS_DEVICE}")
# yolo11x-visdrone.pt")
# yolo11s-visdrone.pt")
HF_URL = "https://huggingface.co/erbayat/yolov11x-visdrone/resolve/main/yolo11x-visdrone.pt"
def _normalized_vehicle_class(cls_name):
    cls = str(cls_name or "").strip().lower()

    if cls in {"van", "auto", "automobile", "vehicle"}:
        return "car"

    if cls in {"motor", "motorbike", "motorcycle"}:
        return "motorcycle"

    return cls
def _vehicle_color_bgr(cls_name):
    cls = _normalized_vehicle_class(cls_name)
    if cls == "truck":
        return (0, 0, 255)
    if cls == "bus":
        return (255, 0, 0)
    if cls == "motorcycle":
        return (0, 0, 0)
    return (0, 255, 0)


def _draw_box_and_label(img, x1, y1, x2, y2, label, color):
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.8
    box_thickness = 2
    text_thickness = 2
    outline_thickness = 5
    pad_x = 8
    pad_y = 6

    cv2.rectangle(img, (int(x1), int(y1)), (int(x2), int(y2)), color, box_thickness)

    (tw, th), baseline = cv2.getTextSize(label, font, font_scale, text_thickness)
    tx = max(0, int(x1))
    ty = max(th + pad_y, int(y1) - 10)

    bg_x1 = tx
    bg_y1 = max(0, ty - th - pad_y)
    bg_x2 = min(img.shape[1] - 1, tx + tw + pad_x * 2)
    bg_y2 = min(img.shape[0] - 1, ty + baseline + pad_y)

    cv2.rectangle(img, (bg_x1, bg_y1), (bg_x2, bg_y2), (0, 0, 0), -1)
    cv2.putText(img, label, (tx + pad_x, ty), font, font_scale, (0, 0, 0), outline_thickness, cv2.LINE_AA)
    cv2.putText(img, label, (tx + pad_x, ty), font, font_scale, (255, 255, 255), text_thickness, cv2.LINE_AA)


def _box_cls_id(b):
    if len(b) > 5:
        try:
            return int(b[5])
        except Exception:
            return None
    return None

def _safe_xyxy_int(x1, y1, x2, y2, W, H):
    if W <= 1 or H <= 1:
        return 0, 0, 0, 0

    x1f = float(min(x1, x2))
    y1f = float(min(y1, y2))
    x2f = float(max(x1, x2))
    y2f = float(max(y1, y2))

    ix1 = int(np.floor(x1f))
    iy1 = int(np.floor(y1f))
    ix2 = int(np.ceil(x2f))
    iy2 = int(np.ceil(y2f))

    ix1 = max(0, min(ix1, W - 1))
    iy1 = max(0, min(iy1, H - 1))
    ix2 = max(0, min(ix2, W - 1))
    iy2 = max(0, min(iy2, H - 1))

    if ix2 <= ix1:
        if ix1 < W - 1:
            ix2 = ix1 + 1
        else:
            ix1 = max(0, ix1 - 1)

    if iy2 <= iy1:
        if iy1 < H - 1:
            iy2 = iy1 + 1
        else:
            iy1 = max(0, iy1 - 1)

    return ix1, iy1, ix2, iy2

def _draw_box_for_tiny_object(img, x1, y1, x2, y2, label, color, min_draw_px=10):
    H, W = img.shape[:2]

    w = max(1, int(x2) - int(x1))
    h = max(1, int(y2) - int(y1))

    if w >= min_draw_px and h >= min_draw_px:
        _draw_box_and_label(img, x1, y1, x2, y2, label, color)
        return

    cx = 0.5 * (int(x1) + int(x2))
    cy = 0.5 * (int(y1) + int(y2))

    half = int(round(min_draw_px / 2))

    dx1 = max(0, int(round(cx)) - half)
    dy1 = max(0, int(round(cy)) - half)
    dx2 = min(W - 1, int(round(cx)) + half)
    dy2 = min(H - 1, int(round(cy)) + half)

    if dx2 <= dx1:
        dx2 = min(W - 1, dx1 + 1)
    if dy2 <= dy1:
        dy2 = min(H - 1, dy1 + 1)

    _draw_box_and_label(img, dx1, dy1, dx2, dy2, label, color)

def _hf_default_cache_dir() -> Path:
    # Кроссплатформенный кэш: Windows/Linux
    base = os.environ.get("VK_HF_CACHE_DIR", "")
    if base.strip():
        return Path(base).expanduser()
    return Path.home() / ".cache" / "traffic" / "hf_weights"

def ensure_hf_weight(hf_url: str, prefer_path: str | None = None) -> str:
    if prefer_path:
        p0 = Path(os.path.expandvars(os.path.expanduser(str(prefer_path)))).resolve()
        if p0.exists():
            return str(p0)

    cache_dir = _hf_default_cache_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)

    filename = os.path.basename(hf_url.split("?")[0]).strip()
    if not filename.lower().endswith(".pt"):
        filename = "model.pt"

    dst = (cache_dir / filename).resolve()
    if dst.exists() and dst.stat().st_size > 0:
        return str(dst)

    # 1) huggingface_hub, если доступен
    if hf_hub_download is not None:
        # Вариант через repo_id/filename (предпочтительно)
        try:
            # для данного URL:
            repo_id = "erbayat/yolov11x-visdrone"
            fname = "yolo11x-visdrone.pt"
            p = hf_hub_download(repo_id=repo_id, filename=fname)
            p = Path(p).resolve()
            if p.exists():
                return str(p)
        except Exception:
            pass

    # 2) Fallback: стандартный urllib (прямой URL)
    import urllib.request
    try:
        urllib.request.urlretrieve(hf_url, str(dst))
    except Exception as e:
        raise RuntimeError(f"Не удалось скачать веса по HF_URL: {hf_url}. Ошибка: {e!r}")

    if not dst.exists() or dst.stat().st_size <= 0:
        raise RuntimeError(f"Скачивание завершилось, но файл пустой: {dst}")

    return str(dst)


def _round32(x: int) -> int:
    return int((x + 31) // 32 * 32)

def reset_dir(p: Path):
    p = Path(p)
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)

def read_image_auto(file_bytes: bytes):
    arr = np.frombuffer(file_bytes, np.uint8)
    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img is not None:
        return img
    pil = PILImage.open(BytesIO(file_bytes))
    pil = ImageOps.exif_transpose(pil).convert("RGB")
    return cv2.cvtColor(np.array(pil), cv2.COLOR_RGB2BGR)

def read_image_path(path: str):
    return read_image_auto(Path(path).read_bytes())

def iter_images(folder: str):
    exts = {".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif"}
    folder = Path(folder)
    for p in sorted(folder.rglob("*")):
        if p.is_file() and p.suffix.lower() in exts:
            yield str(p)

def resolve_paths():
    global DRONE, DATA_SRC, RUNS, DET_ROOT, CLS_ROOT
    DRONE = Path(CFG["DRONE"])
    DATA_SRC = DRONE / CFG["DATA_SRC_REL"]
    RUNS = Path(CFG["RUNS"])
    DET_ROOT = Path(CFG["DET_ROOT"])
    CLS_ROOT = Path(CFG["CLS_ROOT"])
    RUNS.mkdir(parents=True, exist_ok=True)

def resolve_tile_and_sizes(sample_img_path: str | None):
    global TILE, OVERLAP, BASE_IMGSZ, TILED_IMGSZ
    OVERLAP = float(CFG["OVERLAP"])

    tile_cfg = CFG["TILE"]
    if isinstance(tile_cfg, int):
        TILE = int(tile_cfg)
    elif str(tile_cfg).lower() == "auto":
        if sample_img_path is None:
            TILE = int(CFG["AUTO_TILE_TARGET"])
        else:
            img = read_image_path(sample_img_path)
            s = min(img.shape[0], img.shape[1])
            target = int(CFG["AUTO_TILE_TARGET"])
            TILE = _round32(min(s, target))
    else:
        TILE = int(CFG["AUTO_TILE_TARGET"])

    def _auto_imgsz(v):
        if isinstance(v, int):
            return int(v)
        if str(v).lower() == "auto":
            return max(640, _round32(TILE * 2))
        return int(v)

    BASE_IMGSZ  = _auto_imgsz(CFG["BASE_IMGSZ"])
    TILED_IMGSZ = _auto_imgsz(CFG["TILED_IMGSZ"])

def init_data(val_pct: int | None = None):
    global all_imgs, train_imgs, val_imgs
    resolve_paths()

    all_imgs = list(iter_images(str(DATA_SRC)))
    log(f"images_for_training count: {len(all_imgs)}")

    if val_pct is None:
        val_pct = int(CFG["VAL_PCT"])

    def is_val(path: str):
        h = hashlib.md5(Path(path).name.encode("utf-8")).hexdigest()
        return (int(h[:8], 16) % 100) < val_pct

    train_imgs = [p for p in all_imgs if not is_val(p)]
    val_imgs   = [p for p in all_imgs if is_val(p)]
    log(f"split train/val: {len(train_imgs)} / {len(val_imgs)}")

    sample = train_imgs[0] if train_imgs else (val_imgs[0] if val_imgs else None)
    resolve_tile_and_sizes(sample)
    log(f"TILE={TILE}, OVERLAP={OVERLAP}, BASE_IMGSZ={BASE_IMGSZ}, TILED_IMGSZ={TILED_IMGSZ}")

def iou_xyxy(a, b):
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b
    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    iw, ih = max(0, ix2 - ix1), max(0, iy2 - iy1)
    inter = iw * ih
    au = max(0, ax2 - ax1) * max(0, ay2 - ay1)
    bu = max(0, bx2 - bx1) * max(0, by2 - by1)
    return inter / (au + bu - inter + 1e-6)

def nms_union(boxes, thr=0.5):
    if not boxes:
        return []

    max_input = int(CFG.get("NMS_MAX_INPUT", 6000))
    if len(boxes) > max_input:
        boxes = sorted(boxes, key=lambda x: float(x[4]), reverse=True)[:max_input]

    try:
        by_cls = {}
        for b in boxes:
            cls_id = _box_cls_id(b)
            by_cls.setdefault(cls_id, []).append(b)

        kept = []
        for cls_boxes in by_cls.values():
            rects = []
            scores = []
            for b in cls_boxes:
                x1, y1, x2, y2, c = b[:5]
                w = max(1, int(x2) - int(x1))
                h = max(1, int(y2) - int(y1))
                rects.append([int(x1), int(y1), w, h])
                scores.append(float(c))

            idxs = cv2.dnn.NMSBoxes(rects, scores, score_threshold=0.0, nms_threshold=float(thr))
            if idxs is None or len(idxs) == 0:
                continue

            for i in np.array(idxs).reshape(-1).tolist():
                kept.append(cls_boxes[int(i)])

        kept.sort(key=lambda x: float(x[4]), reverse=True)
        return kept
    except Exception:
        boxes = sorted(boxes, key=lambda x: x[4], reverse=True)
        kept = []
        for b in boxes:
            drop = False
            for k in kept:
                cls_b = _box_cls_id(b)
                cls_k = _box_cls_id(k)
                if cls_b is not None and cls_k is not None and cls_b != cls_k:
                    continue
                if iou_xyxy(b[:4], k[:4]) > thr:
                    drop = True
                    break
            if not drop:
                kept.append(b)
        return kept

def refine_boxes_by_vote(kept_boxes, source_boxes, vote_iou=0.35):
    if not kept_boxes or not source_boxes:
        return kept_boxes

    out = []
    for kb in kept_boxes:
        kx1, ky1, kx2, ky2, kc = kb[:5]
        ktail = tuple(kb[5:])
        kcls = _box_cls_id(kb)

        sx1 = float(kx1) * float(max(kc, 1e-6))
        sy1 = float(ky1) * float(max(kc, 1e-6))
        sx2 = float(kx2) * float(max(kc, 1e-6))
        sy2 = float(ky2) * float(max(kc, 1e-6))
        sw = float(max(kc, 1e-6))
        best_c = float(kc)

        for sb in source_boxes:
            scls = _box_cls_id(sb)
            if kcls is not None and scls is not None and kcls != scls:
                continue
            if iou_xyxy(kb[:4], sb[:4]) < float(vote_iou):
                continue

            sc = float(sb[4])
            bx1, by1, bx2, by2 = sb[:4]
            w = max(sc, 1e-6)
            sx1 += float(bx1) * w
            sy1 += float(by1) * w
            sx2 += float(bx2) * w
            sy2 += float(by2) * w
            sw += w
            if sc > best_c:
                best_c = sc

        if sw > 0.0:
            rx1 = int(round(sx1 / sw))
            ry1 = int(round(sy1 / sw))
            rx2 = int(round(sx2 / sw))
            ry2 = int(round(sy2 / sw))
        else:
            rx1, ry1, rx2, ry2 = int(kx1), int(ky1), int(kx2), int(ky2)

        out.append((rx1, ry1, rx2, ry2, float(best_c), *ktail))

    out.sort(key=lambda x: float(x[4]), reverse=True)
    return out

def _vk_expand_xyxy(x1, y1, x2, y2, frac, W, H):
    w = max(1.0, float(x2) - float(x1))
    h = max(1.0, float(y2) - float(y1))
    dx = float(frac) * w
    dy = float(frac) * h
    xx1 = max(0.0, float(x1) - dx)
    yy1 = max(0.0, float(y1) - dy)
    xx2 = min(float(W - 1), float(x2) + dx)
    yy2 = min(float(H - 1), float(y2) + dy)
    return (xx1, yy1, xx2, yy2)

def _vk_interval_gap(a1, a2, b1, b2):
    a1 = float(a1); a2 = float(a2); b1 = float(b1); b2 = float(b2)
    if a2 < b1:
        return b1 - a2
    if b2 < a1:
        return a1 - b2
    return 0.0

def _vk_axis_overlap_ratio(a1, a2, b1, b2):
    a1 = float(a1); a2 = float(a2); b1 = float(b1); b2 = float(b2)
    ov = max(0.0, min(a2, b2) - max(a1, b1))
    denom = max(1e-6, min(a2 - a1, b2 - b1))
    return ov / denom

def _vk_merge_parts_union(boxes, W, H,
                          iou_thr=0.25,
                          exp_frac=0.25,
                          exp_iou_thr=0.05,
                          axis_ov_thr=0.60,
                          gap_frac=0.35,
                          center_frac=2.0):
    if not boxes:
        return []

    n = len(boxes)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def unite(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    P = []
    for box in boxes:
        x1, y1, x2, y2, c = box[:5]
        tail = tuple(box[5:])
        x1f = float(x1)
        y1f = float(y1)
        x2f = float(x2)
        y2f = float(y2)
        w = max(1.0, x2f - x1f)
        h = max(1.0, y2f - y1f)
        cx = 0.5 * (x1f + x2f)
        cy = 0.5 * (y1f + y2f)
        P.append((x1f, y1f, x2f, y2f, float(c), w, h, cx, cy, tail))

    for i in range(n):
        x1i, y1i, x2i, y2i, ci, wi, hi, cxi, cyi, tail_i = P[i]
        cls_i = tail_i[0] if len(tail_i) > 0 else None

        for j in range(i + 1, n):
            x1j, y1j, x2j, y2j, cj, wj, hj, cxj, cyj, tail_j = P[j]
            cls_j = tail_j[0] if len(tail_j) > 0 else None

            if cls_i is not None and cls_j is not None and cls_i != cls_j:
                continue
            if abs(cxi - cxj) > float(center_frac) * max(wi, wj):
                continue
            if abs(cyi - cyj) > float(center_frac) * max(hi, hj):
                continue

            if iou_xyxy((x1i, y1i, x2i, y2i), (x1j, y1j, x2j, y2j)) >= float(iou_thr):
                unite(i, j)
                continue

            ei = _vk_expand_xyxy(x1i, y1i, x2i, y2i, exp_frac, W, H)
            ej = _vk_expand_xyxy(x1j, y1j, x2j, y2j, exp_frac, W, H)
            if iou_xyxy(ei, ej) >= float(exp_iou_thr):
                unite(i, j)
                continue

            yov = _vk_axis_overlap_ratio(y1i, y2i, y1j, y2j)
            xov = _vk_axis_overlap_ratio(x1i, x2i, x1j, x2j)
            xgap = _vk_interval_gap(x1i, x2i, x1j, x2j)
            ygap = _vk_interval_gap(y1i, y2i, y1j, y2j)

            if (yov >= float(axis_ov_thr)) and (xgap <= float(gap_frac) * max(wi, wj)):
                unite(i, j)
                continue
            if (xov >= float(axis_ov_thr)) and (ygap <= float(gap_frac) * max(hi, hj)):
                unite(i, j)
                continue

    clusters = {}
    for idx in range(n):
        r = find(idx)
        clusters.setdefault(r, []).append(idx)

    merged = []
    for comp in clusters.values():
        x1 = min(P[k][0] for k in comp)
        y1 = min(P[k][1] for k in comp)
        x2 = max(P[k][2] for k in comp)
        y2 = max(P[k][3] for k in comp)

        best_k = max(comp, key=lambda k: P[k][4])
        c = P[best_k][4]
        tail = P[best_k][9]

        x1 = int(max(0, min(int(round(x1)), W - 1)))
        y1 = int(max(0, min(int(round(y1)), H - 1)))
        x2 = int(max(0, min(int(round(x2)), W - 1)))
        y2 = int(max(0, min(int(round(y2)), H - 1)))

        if x2 > x1 and y2 > y1:
            merged.append((x1, y1, x2, y2, float(c), *tail))

    merged.sort(key=lambda t: t[4], reverse=True)
    return merged

def filter_boxes_geom(boxes, cfg=None):
    if cfg is None:
        return boxes
    out = []
    ar_min = float(cfg.get("ar_min", 0.25))
    ar_max = float(cfg.get("ar_max", 5.0))
    min_side = int(cfg.get("min_side", 4))
    for box in boxes:
        x1, y1, x2, y2, c = box[:5]
        tail = tuple(box[5:])
        w = x2 - x1
        h = y2 - y1
        if w <= 0 or h <= 0:
            continue
        s = min(w, h)
        if s < min_side:
            continue
        ar = w / float(h)
        if ar < ar_min or ar > ar_max:
            continue
        out.append((x1, y1, x2, y2, c, *tail))
    return out

def crop_with_pad(img, x1, y1, x2, y2, pad=0.8):
    H, W = img.shape[:2]
    w = x2 - x1
    h = y2 - y1
    cx = (x1 + x2) / 2
    cy = (y1 + y2) / 2
    nw = w * (1 + pad)
    nh = h * (1 + pad)

    rx1 = int(max(0, cx - nw / 2))
    ry1 = int(max(0, cy - nh / 2))
    rx2 = int(min(W, cx + nw / 2))
    ry2 = int(min(H, cy + nh / 2))
    if rx2 <= rx1 or ry2 <= ry1:
        return None
    return img[ry1:ry2, rx1:rx2]

def ensure_det_dirs(root: Path):
    for p in ["train/images", "train/labels", "val/images", "val/labels"]:
        (Path(root) / p).mkdir(parents=True, exist_ok=True)

def ensure_cls_dirs(root: Path):
    for p in ["train/car", "train/bg", "val/car", "val/bg"]:
        (Path(root) / p).mkdir(parents=True, exist_ok=True)

def get_keep_class_ids(model, keep_names: set[str] | None):
    if keep_names is None:
        return None

    keep_norm = {_normalized_vehicle_class(str(x).strip().lower()) for x in keep_names if str(x).strip()}
    names = model.names

    ids = []

    if isinstance(names, dict):
        for i, n in names.items():
            raw = str(n).strip().lower()
            norm = _normalized_vehicle_class(raw)
            if raw in keep_norm or norm in keep_norm:
                ids.append(int(i))
    else:
        for i, n in enumerate(names):
            raw = str(n).strip().lower()
            norm = _normalized_vehicle_class(raw)
            if raw in keep_norm or norm in keep_norm:
                ids.append(int(i))

    return sorted(ids)

_DET_MODEL = None
_DET_MODEL_PATH = None

def resolve_model_path() -> Path:
    candidates = []

    p = Path(CFG.get("MODEL_PATH", ""))
    if p and p.exists():
        return p

    drone = Path(CFG["DRONE"])
    for rel in ["data_det", "models", "weights", "runs", "."]:
        d = drone / rel
        if d.exists():
            candidates.extend(sorted(d.rglob("*.pt")))

    for d in [Path("/content"), Path("/content/runs"), Path(CFG["RUNS"]), Path(CFG["DET_ROOT"]), Path(CFG["CLS_ROOT"])]:
        if d.exists():
            candidates.extend(sorted(d.rglob("*.pt")))

    uniq = []
    seen = set()
    for c in candidates:
        c = c.resolve()
        if c not in seen:
            uniq.append(c)
            seen.add(c)

    if not uniq:
        raise FileNotFoundError(
            "Не найдено ни одного файла весов *.pt.\n"
            "Проверьте, что в Google Drive реально есть веса, и что DRONE указывает на правильную папку.\n"
            f"DRONE={drone}\n"
            f"Ожидаемые места: {drone/'data_det'} или любой подкаталог DRONE, либо /content."
        )

    if len(uniq) == 1:
        CFG["MODEL_PATH"] = str(uniq[0])
        log(f"auto-selected MODEL_PATH: {CFG['MODEL_PATH']}")
        return uniq[0]

    raise FileNotFoundError(
        "Найдено несколько файлов весов *.pt. "
        "Интерактивный выбор отключён. "
        "Укажите точный путь в CFG['MODEL_PATH'] или передайте model_path через cfg в run()."
    )


def get_det_model():
    global _DET_MODEL, _DET_MODEL_PATH

    mp = resolve_model_path()
    mp_str = str(mp)

    if _DET_MODEL is None or _DET_MODEL_PATH != mp_str:
        log(f"loading det model: {mp}")
        _DET_MODEL = YOLO(mp_str)
        _DET_MODEL_PATH = mp_str

    return _DET_MODEL

def predict_boxes(model, img_bgr, conf, iou, imgsz, max_det, keep_ids=None):
    H, W = img_bgr.shape[:2]

    r = model.predict(
        img_bgr,
        conf=float(conf),
        iou=float(iou),
        imgsz=int(imgsz),
        max_det=int(max_det),
        classes=list(keep_ids) if keep_ids is not None else None,
        device=PRED_DEVICE,
        verbose=False
    )[0]

    names = model.names
    out = []

    for b in r.boxes:
        cls_id = int(b.cls.item())
        if keep_ids is not None and cls_id not in keep_ids:
            continue

        cls_name = names.get(cls_id, str(cls_id)) if isinstance(names, dict) else names[cls_id]
        cls_name = _normalized_vehicle_class(cls_name)

        x1, y1, x2, y2 = b.xyxy[0].detach().cpu().numpy().tolist()
        x1, y1, x2, y2 = _safe_xyxy_int(x1, y1, x2, y2, W, H)

        if x2 <= x1 or y2 <= y1:
            continue

        out.append((x1, y1, x2, y2, float(b.conf.item()), int(cls_id), str(cls_name)))

    return out

def detect_tiled_fast(model, img_bgr,
                      conf=None, iou=None, imgsz=None, max_det=None,
                      nms_thr=None, batch=None, tile=None, overlap=None,
                      keep_ids=None):
    if conf is None:
        conf = float(CFG["DET_CONF"])
    if iou is None:
        iou = float(CFG["DET_IOU"])
    if imgsz is None:
        imgsz = int(TILED_IMGSZ)
    if max_det is None:
        max_det = int(CFG["DET_MAX_DET"])
    if nms_thr is None:
        nms_thr = float(CFG["DET_NMS_THR"])
    if batch is None:
        batch = int(CFG["TILED_BATCH"])
    if tile is None:
        tile = int(TILE)
    if overlap is None:
        overlap = float(OVERLAP)

    H, W = img_bgr.shape[:2]
    if tile > H or tile > W:
        tile = int(min(tile, H, W))
    stride = max(1, int(tile * (1 - overlap)))

    xs = list(range(0, max(1, W - tile + 1), stride))
    ys = list(range(0, max(1, H - tile + 1), stride))
    if W >= tile and xs and xs[-1] != W - tile:
        xs.append(W - tile)
    if H >= tile and ys and ys[-1] != H - tile:
        ys.append(H - tile)

    xs = sorted(set(max(0, min(x, max(0, W - tile))) for x in xs))
    ys = sorted(set(max(0, min(y, max(0, H - tile))) for y in ys))

    tiles = []
    offs = []
    for ty in ys:
        for tx in xs:
            t = img_bgr[ty:ty + tile, tx:tx + tile]
            if t.shape[0] == tile and t.shape[1] == tile:
                tiles.append(t)
                offs.append((tx, ty))

    if not tiles:
        return nms_union(
            predict_boxes(model, img_bgr, conf, iou, imgsz, max_det, keep_ids=keep_ids),
            thr=nms_thr
        )

    names = model.names
    all_boxes = []
    for i0 in range(0, len(tiles), batch):
        chunk = tiles[i0:i0 + batch]
        chunk_offs = offs[i0:i0 + batch]
        rs = model.predict(
            chunk,
            conf=conf,
            iou=iou,
            imgsz=imgsz,
            max_det=max_det,
            classes=list(keep_ids) if keep_ids is not None else None,
            device=PRED_DEVICE,
            verbose=False
        )
        for r, (tx, ty) in zip(rs, chunk_offs):
            for b in r.boxes:
                cls_id = int(b.cls.item())
                if keep_ids is not None and cls_id not in keep_ids:
                    continue

                cls_name = names.get(cls_id, str(cls_id)) if isinstance(names, dict) else names[cls_id]
                cls_name = _normalized_vehicle_class(cls_name)

                x1, y1, x2, y2 = b.xyxy[0].detach().cpu().numpy().tolist()
                x1, y1, x2, y2 = _safe_xyxy_int(x1, y1, x2, y2, tile, tile)

                all_boxes.append(
                    (x1 + tx, y1 + ty, x2 + tx, y2 + ty, float(b.conf.item()), int(cls_id), str(cls_name))
                )

    return nms_union(all_boxes, thr=nms_thr)

def detect_tiled(model, img_bgr, **kwargs):
    return detect_tiled_fast(model, img_bgr, **kwargs)

def _select_informative_offsets(img_bgr, tile, overlap, keep_ratio=0.35, max_tiles=220, min_tiles=24):
    H, W = img_bgr.shape[:2]
    tile = max(8, min(int(tile), H, W))
    stride = max(1, int(tile * (1 - float(overlap))))

    xs = list(range(0, max(1, W - tile + 1), stride))
    ys = list(range(0, max(1, H - tile + 1), stride))
    if W >= tile and xs and xs[-1] != W - tile:
        xs.append(W - tile)
    if H >= tile and ys and ys[-1] != H - tile:
        ys.append(H - tile)
    xs = sorted(set(max(0, min(x, max(0, W - tile))) for x in xs))
    ys = sorted(set(max(0, min(y, max(0, H - tile))) for y in ys))

    if not xs or not ys:
        return [(0, 0)]

    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    lap = cv2.Laplacian(gray, cv2.CV_16S, ksize=3)
    lap_abs = cv2.convertScaleAbs(lap)
    integ = cv2.integral(lap_abs, sdepth=cv2.CV_64F)

    scored = []
    for ty in ys:
        y2 = ty + tile
        for tx in xs:
            x2 = tx + tile
            s = integ[y2, x2] - integ[ty, x2] - integ[y2, tx] + integ[ty, tx]
            scored.append((float(s), tx, ty))

    scored.sort(key=lambda t: t[0], reverse=True)
    total = len(scored)
    k = int(round(total * float(keep_ratio)))
    k = max(int(min_tiles), k)
    k = min(total, int(max_tiles), k)
    return [(tx, ty) for _, tx, ty in scored[:k]]

def _detect_distant_roi_boxes(model, img_bgr, conf, iou, imgsz, max_det, nms_thr, batch, keep_ids=None):
    H, W = img_bgr.shape[:2]
    if H <= 2 or W <= 2:
        return []

    # Дальний план обычно в верхней части кадра и ближе к центральной перспективе дороги.
    y_end_frac = float(CFG.get("DISTANT_ROI_Y_END_FRAC", 0.50))
    x_l_frac = float(CFG.get("DISTANT_ROI_X_LEFT_FRAC", 0.10))
    x_r_frac = float(CFG.get("DISTANT_ROI_X_RIGHT_FRAC", 0.90))
    d_overlap = float(CFG.get("DISTANT_OVERLAP", 0.35))
    d_tiles = CFG.get("DISTANT_TILE_SIZES", [192, 128, 96, 64])
    d_scales = CFG.get("DISTANT_UPSCALE_FACTORS", [1.0, 2.0])
    d_keep_ratio = float(CFG.get("DISTANT_TILE_KEEP_RATIO", 0.35))
    d_max_tiles = int(CFG.get("DISTANT_MAX_TILES", 220))
    d_min_tiles = int(CFG.get("DISTANT_MIN_TILES", 24))

    y0 = 0
    y1 = int(round(max(0.05, min(0.95, y_end_frac)) * H))
    x0 = int(round(max(0.0, min(0.8, x_l_frac)) * W))
    x1 = int(round(max(0.2, min(1.0, x_r_frac)) * W))

    y1 = max(y0 + 2, min(H, y1))
    x1 = max(x0 + 2, min(W, x1))

    roi = img_bgr[y0:y1, x0:x1]
    if roi.size == 0:
        return []

    out = []
    names = model.names
    for sc in d_scales:
        try:
            scale = float(sc)
        except Exception:
            continue
        if scale < 1.0:
            continue

        if scale > 1.001:
            sw = max(2, int(round(roi.shape[1] * scale)))
            sh = max(2, int(round(roi.shape[0] * scale)))
            roi_s = cv2.resize(roi, (sw, sh), interpolation=cv2.INTER_CUBIC)
        else:
            roi_s = roi

        used = set()
        for tv in d_tiles:
            try:
                tile = int(tv)
            except Exception:
                continue
            if tile <= 0:
                continue

            tile_s = max(64, int(round(tile * scale)))
            tile_s = max(64, min(tile_s, roi_s.shape[0], roi_s.shape[1]))
            if tile_s in used:
                continue
            used.add(tile_s)

            offs = _select_informative_offsets(
                roi_s,
                tile=tile_s,
                overlap=d_overlap,
                keep_ratio=d_keep_ratio,
                max_tiles=d_max_tiles,
                min_tiles=d_min_tiles
            )
            if not offs:
                continue

            boxes_roi = []
            for i0 in range(0, len(offs), batch):
                chunk_offs = offs[i0:i0 + batch]
                chunk = [roi_s[ty:ty + tile_s, tx:tx + tile_s] for (tx, ty) in chunk_offs]
                rs = model.predict(
                    chunk,
                    conf=conf,
                    iou=iou,
                    imgsz=imgsz,
                    max_det=max_det,
                    classes=list(keep_ids) if keep_ids is not None else None,
                    device=PRED_DEVICE,
                    verbose=False
                )
                for r, (tx, ty) in zip(rs, chunk_offs):
                    for b in r.boxes:
                        cls_id = int(b.cls.item())
                        if keep_ids is not None and cls_id not in keep_ids:
                            continue
                        cls_name = names.get(cls_id, str(cls_id)) if isinstance(names, dict) else names[cls_id]
                        cls_name = _normalized_vehicle_class(cls_name)
                        bx1, by1, bx2, by2 = b.xyxy[0].detach().cpu().numpy().tolist()
                        bx1, by1, bx2, by2 = _safe_xyxy_int(bx1, by1, bx2, by2, tile_s, tile_s)
                        boxes_roi.append((bx1 + tx, by1 + ty, bx2 + tx, by2 + ty, float(b.conf.item()), int(cls_id), str(cls_name)))

            for b in boxes_roi:
                x1b, y1b, x2b, y2b, c = b[:5]
                tail = tuple(b[5:])
                if scale > 1.001:
                    x1b /= scale
                    y1b /= scale
                    x2b /= scale
                    y2b /= scale
                out.append((int(x1b) + x0, int(y1b) + y0, int(x2b) + x0, int(y2b) + y0, float(c), *tail))

    return nms_union(out, thr=nms_thr)

def detect_vehicle_candidates_max_recall(model, img_bgr, keep_ids=None, use_tiles=True):
    H, W = img_bgr.shape[:2]

    conf = float(CFG["DET_CONF"])
    iou = float(CFG["DET_IOU"])
    imgsz = int(TILED_IMGSZ)
    max_det = int(CFG["DET_MAX_DET"])
    nms_thr = float(CFG["DET_NMS_THR"])
    batch = int(CFG["TILED_BATCH"])
    overlap = float(OVERLAP)

    all_boxes = []

    full_boxes = predict_boxes(
        model,
        img_bgr,
        conf=conf,
        iou=iou,
        imgsz=imgsz,
        max_det=max_det,
        keep_ids=keep_ids
    )
    all_boxes.extend(full_boxes)

    tiled_total = 0

    if use_tiles:
        tile_sizes = CFG.get("TILE_SIZES", [640, 320, 256])
        used = set()

        for tile_value in tile_sizes:
            try:
                tile = int(tile_value)
            except Exception:
                continue

            if tile <= 0:
                continue

            tile = max(64, min(tile, H, W))

            if tile in used:
                continue

            used.add(tile)

            tiled_boxes = detect_tiled(
                model,
                img_bgr,
                conf=conf,
                iou=iou,
                imgsz=imgsz,
                max_det=max_det,
                nms_thr=nms_thr,
                tile=tile,
                overlap=overlap,
                batch=batch,
                keep_ids=keep_ids
            )

            tiled_total += len(tiled_boxes)
            all_boxes.extend(tiled_boxes)

        if bool(CFG.get("DISTANT_ROI_ENABLED", True)):
            d_conf = float(CFG.get("DISTANT_CONF", max(1e-6, conf * 0.35)))
            d_iou = float(CFG.get("DISTANT_IOU", iou))
            d_max_det = int(CFG.get("DISTANT_MAX_DET", max_det))
            d_batch = int(CFG.get("DISTANT_BATCH", max(1, batch)))

            distant_boxes = _detect_distant_roi_boxes(
                model,
                img_bgr,
                conf=d_conf,
                iou=d_iou,
                imgsz=imgsz,
                max_det=d_max_det,
                nms_thr=nms_thr,
                batch=d_batch,
                keep_ids=keep_ids
            )
            tiled_total += len(distant_boxes)
            all_boxes.extend(distant_boxes)

    boxes = nms_union(all_boxes, thr=nms_thr)
    if bool(CFG.get("BOX_VOTE_REFINE", True)):
        boxes = refine_boxes_by_vote(
            boxes,
            all_boxes,
            vote_iou=float(CFG.get("BOX_VOTE_IOU", 0.35))
        )

    return boxes, len(full_boxes), tiled_total

def run(image_path: str, out_dir: str, cfg: dict, device_mode: str = "auto") -> dict:
    global PRED_DEVICE, TILE, OVERLAP, BASE_IMGSZ, TILED_IMGSZ

    t0 = time.time()
    os.makedirs(out_dir, exist_ok=True)

    warnings = []

    nb = (cfg.get("notebooks", {}) or {}).get("vehicle_detect", {}) or {}
    det_cfg = (cfg.get("detector", {}) or {})
    pp_cfg = (cfg.get("postprocess", {}) or {})
    un_cfg = (cfg.get("union_nms", {}) or {})
    visual_cfg = (cfg.get("visual", {}) or {})

    model_path = str(cfg.get("yolo_model_path", "") or "").strip().strip('"').strip("'")
    if not model_path:
        raise FileNotFoundError("Не задан yolo_model_path в cfg")

    model_path = os.path.expandvars(os.path.expanduser(model_path))

    if not Path(model_path).is_absolute():
        ydir = str(cfg.get("yolo_dir", "") or "").strip()
        ydir = os.path.expandvars(os.path.expanduser(ydir))
        if ydir:
            model_path = str((Path(ydir) / model_path).resolve())

    if not Path(model_path).exists():
        raise FileNotFoundError(f"Файл весов не найден: {model_path}")

    CFG["MODEL_PATH"] = model_path

    keep_names = pp_cfg.get("keep_classes", None)
    if keep_names:
        CFG["KEEP_CLASS_NAMES"] = {
            _normalized_vehicle_class(str(x).strip().lower())
            for x in keep_names
            if str(x).strip()
        }

    # Быстрый high-recall режим без апскейла/аугментаций
    CFG["DET_CONF"] = float(nb.get("conf", det_cfg.get("conf", 0.0003)))
    CFG["DET_IOU"] = float(nb.get("iou", det_cfg.get("iou", 0.95)))
    CFG["DET_MAX_DET"] = int(nb.get("max_det", det_cfg.get("max_det", 16000)))

    if bool(un_cfg.get("enabled", True)):
        CFG["DET_NMS_THR"] = float(un_cfg.get("iou", 0.97))
    else:
        CFG["DET_NMS_THR"] = float(nb.get("nms_thr", det_cfg.get("nms_thr", 0.97)))

    CFG["TILED_BATCH"] = int(nb.get("tiled_batch", det_cfg.get("tiled_batch", 8)))
    CFG["OVERLAP"] = float(nb.get("overlap", det_cfg.get("overlap", 0.22)))
    CFG["DISTANT_ROI_ENABLED"] = bool(nb.get("distant_roi_enabled", det_cfg.get("distant_roi_enabled", True)))
    CFG["DISTANT_ROI_Y_END_FRAC"] = float(nb.get("distant_roi_y_end_frac", det_cfg.get("distant_roi_y_end_frac", 0.52)))
    CFG["DISTANT_ROI_X_LEFT_FRAC"] = float(nb.get("distant_roi_x_left_frac", det_cfg.get("distant_roi_x_left_frac", 0.08)))
    CFG["DISTANT_ROI_X_RIGHT_FRAC"] = float(nb.get("distant_roi_x_right_frac", det_cfg.get("distant_roi_x_right_frac", 0.92)))
    CFG["DISTANT_TILE_SIZES"] = list(nb.get("distant_tile_sizes", det_cfg.get("distant_tile_sizes", [256, 192, 128, 96, 64])))
    CFG["DISTANT_UPSCALE_FACTORS"] = list(nb.get("distant_upscale_factors", det_cfg.get("distant_upscale_factors", [1.0, 2.0])))
    CFG["DISTANT_OVERLAP"] = float(nb.get("distant_overlap", det_cfg.get("distant_overlap", 0.35)))
    CFG["DISTANT_CONF"] = float(nb.get("distant_conf", det_cfg.get("distant_conf", 0.00003)))
    CFG["DISTANT_IOU"] = float(nb.get("distant_iou", det_cfg.get("distant_iou", 0.95)))
    CFG["DISTANT_MAX_DET"] = int(nb.get("distant_max_det", det_cfg.get("distant_max_det", 20000)))
    CFG["DISTANT_BATCH"] = int(nb.get("distant_batch", det_cfg.get("distant_batch", 6)))
    CFG["DISTANT_TILE_KEEP_RATIO"] = float(nb.get("distant_tile_keep_ratio", det_cfg.get("distant_tile_keep_ratio", 0.35)))
    CFG["DISTANT_MAX_TILES"] = int(nb.get("distant_max_tiles", det_cfg.get("distant_max_tiles", 220)))
    CFG["DISTANT_MIN_TILES"] = int(nb.get("distant_min_tiles", det_cfg.get("distant_min_tiles", 24)))
    CFG["DISTANT_RELAX_POSTFILTER"] = bool(nb.get("distant_relax_postfilter", det_cfg.get("distant_relax_postfilter", True)))
    CFG["DISTANT_TINY_MAX_SIDE"] = int(nb.get("distant_tiny_max_side", det_cfg.get("distant_tiny_max_side", 8)))
    CFG["NMS_MAX_INPUT"] = int(nb.get("nms_max_input", det_cfg.get("nms_max_input", 6000)))
    CFG["BOX_VOTE_REFINE"] = bool(nb.get("box_vote_refine", det_cfg.get("box_vote_refine", True)))
    CFG["BOX_VOTE_IOU"] = float(nb.get("box_vote_iou", det_cfg.get("box_vote_iou", 0.35)))

    img = read_image_path(image_path)
    H, W = img.shape[:2]

    target = int(nb.get("imgsz", det_cfg.get("imgsz", 1280)) or 1280)
    target = max(640, _round32(target))

    BASE_IMGSZ = target
    TILED_IMGSZ = target
    CFG["BASE_IMGSZ"] = target
    CFG["TILED_IMGSZ"] = target

    tile_sizes_cfg = nb.get("tile_sizes", det_cfg.get("tile_sizes", [640, 384, 256, 192]))

    parsed_tile_sizes = []

    if isinstance(tile_sizes_cfg, list):
        tile_source = tile_sizes_cfg
    else:
        tile_source = [tile_sizes_cfg]

    for value in tile_source:
        try:
            tile_value = int(value)
        except Exception:
            continue

        if tile_value > 0:
            parsed_tile_sizes.append(tile_value)

    if not parsed_tile_sizes:
        parsed_tile_sizes = [640, 384, 256, 192]

    CFG["TILE_SIZES"] = parsed_tile_sizes

    tile_v = nb.get("tile", det_cfg.get("tile", parsed_tile_sizes[0]))

    if str(tile_v).lower() in {"auto", ""}:
        TILE = max(64, min(int(parsed_tile_sizes[0]), H, W))
    else:
        TILE = max(64, min(int(tile_v), H, W))

    OVERLAP = float(CFG["OVERLAP"])
    CFG["TILE"] = int(TILE)

    prefer_gpu = (device_mode or "auto") != "cpu"
    PRED_DEVICE = pick_device(prefer_gpu=prefer_gpu)
    device_used = "gpu" if PRED_DEVICE != "cpu" else "cpu"

    # На CPU ограничиваем взрыв кандидатов в YOLO NMS (иначе предупреждение time limit exceeded).
    if PRED_DEVICE == "cpu":
        CFG["DET_MAX_DET"] = int(min(int(CFG.get("DET_MAX_DET", 16000)), int(nb.get("cpu_det_max_det", 3500))))
        CFG["DISTANT_MAX_DET"] = int(min(int(CFG.get("DISTANT_MAX_DET", 20000)), int(nb.get("cpu_distant_max_det", 4500))))
        CFG["NMS_MAX_INPUT"] = int(min(int(CFG.get("NMS_MAX_INPUT", 6000)), int(nb.get("cpu_nms_max_input", 2200))))
        CFG["DISTANT_MAX_TILES"] = int(min(int(CFG.get("DISTANT_MAX_TILES", 220)), int(nb.get("cpu_distant_max_tiles", 80))))
        CFG["DISTANT_MIN_TILES"] = int(min(int(CFG.get("DISTANT_MIN_TILES", 24)), int(nb.get("cpu_distant_min_tiles", 12))))
        CFG["DISTANT_UPSCALE_FACTORS"] = list(nb.get("cpu_distant_upscale_factors", [1.0, 2.0]))
        CFG["DISTANT_TILE_KEEP_RATIO"] = float(min(float(CFG.get("DISTANT_TILE_KEEP_RATIO", 0.35)), float(nb.get("cpu_distant_tile_keep_ratio", 0.15))))
        CFG["TILED_BATCH"] = int(max(1, nb.get("cpu_tiled_batch", max(1, int(CFG.get("TILED_BATCH", 8))))))
        target = int(min(int(target), int(nb.get("cpu_imgsz", 960))))
        BASE_IMGSZ = max(640, _round32(target))
        TILED_IMGSZ = BASE_IMGSZ
        CFG["BASE_IMGSZ"] = BASE_IMGSZ
        CFG["TILED_IMGSZ"] = TILED_IMGSZ
        warnings.append("cpu_fast_profile_enabled")

    if (device_mode or "auto") == "gpu" and device_used != "gpu":
        warnings.append("gpu_requested_but_unavailable")

    det = get_det_model()
    keep_ids = get_keep_class_ids(det, CFG["KEEP_CLASS_NAMES"])

    use_tiles = bool(nb.get("use_tiles", det_cfg.get("use_tiles", True)))

    t_inf0 = time.time()

    boxes, full_count, tiled_count = detect_vehicle_candidates_max_recall(
        det,
        img,
        keep_ids=keep_ids,
        use_tiles=use_tiles
    )

    t_inf1 = time.time()

    if bool(pp_cfg.get("enabled", False)) and boxes:
        min_conf = float(pp_cfg.get("min_conf", 0.0))
        min_box_px = int(pp_cfg.get("min_box_px", 1))
        min_area_frac = float(pp_cfg.get("min_area_frac", 0.0))
        ar_min = float(pp_cfg.get("aspect_ratio_min", 0.0))
        ar_max = float(pp_cfg.get("aspect_ratio_max", 1e9))
        ex_top = float(pp_cfg.get("exclude_top_frac", 0.0))
        ex_bot = float(pp_cfg.get("exclude_bottom_frac", 0.0))

        img_area = float(W * H) if W > 0 and H > 0 else 0.0
        y_top = int(round(ex_top * H))
        y_bot = int(round((1.0 - ex_bot) * H))
        distant_relax = bool(CFG.get("DISTANT_RELAX_POSTFILTER", True))
        distant_tiny_max_side = int(CFG.get("DISTANT_TINY_MAX_SIDE", 8))
        distant_y_lim = int(round(float(CFG.get("DISTANT_ROI_Y_END_FRAC", 0.52)) * H))

        filtered = []

        for box in boxes:
            x1, y1, x2, y2, c = box[:5]
            tail = tuple(box[5:])

            x1, y1, x2, y2 = _safe_xyxy_int(x1, y1, x2, y2, W, H)

            c = float(c)
            if c < min_conf:
                continue

            bw = int(x2) - int(x1)
            bh = int(y2) - int(y1)
            cy = (int(y1) + int(y2)) // 2
            is_distant_tiny = distant_relax and (max(bw, bh) <= distant_tiny_max_side) and (cy <= distant_y_lim)

            min_side_req = 1 if is_distant_tiny else min_box_px
            if bw < min_side_req or bh < min_side_req:
                continue

            if (not is_distant_tiny) and img_area > 0.0 and (bw * bh) < (min_area_frac * img_area):
                continue

            if (not is_distant_tiny) and bw > 0 and bh > 0:
                ar = float(bw) / float(bh)
                if ar < ar_min or ar > ar_max:
                    continue

            if (not is_distant_tiny) and (cy < y_top or cy > y_bot):
                continue

            filtered.append((int(x1), int(y1), int(x2), int(y2), c, *tail))

        boxes = filtered

    mp_cfg = (pp_cfg.get("merge_parts", {}) or {})
    if bool(mp_cfg.get("enabled", False)) and boxes:
        boxes = _vk_merge_parts_union(
            boxes,
            W=W,
            H=H,
            iou_thr=float(mp_cfg.get("iou_thr", 0.25)),
            exp_frac=float(mp_cfg.get("exp_frac", 0.25)),
            exp_iou_thr=float(mp_cfg.get("exp_iou_thr", 0.05)),
            axis_ov_thr=float(mp_cfg.get("axis_ov_thr", 0.60)),
            gap_frac=float(mp_cfg.get("gap_frac", 0.35)),
            center_frac=float(mp_cfg.get("center_frac", 2.0)),
        )

    dets = []
    vis = img.copy()
    brightness = round(float(np.mean(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))), 2)

    min_draw_px = int(visual_cfg.get("min_draw_px", 12))

    for i, box in enumerate(boxes, 1):
        x1, y1, x2, y2, c = box[:5]
        cls_id = int(box[5]) if len(box) > 5 else 0
        cls_name = _normalized_vehicle_class(box[6] if len(box) > 6 else "vehicle")

        x1, y1, x2, y2 = _safe_xyxy_int(x1, y1, x2, y2, W, H)

        if x2 <= x1 or y2 <= y1:
            continue

        w_px = int(x2 - x1)
        h_px = int(y2 - y1)
        cluster_metric = f"{w_px}x{h_px}px"

        color = _vehicle_color_bgr(cls_name)
        label = f"{cls_name} {i} {cluster_metric}"
        _draw_box_for_tiny_object(vis, x1, y1, x2, y2, label, color, min_draw_px=min_draw_px)

        dets.append(
            {
                "bbox_xyxy": [x1, y1, x2, y2],
                "conf": float(c),
                "cls_id": int(cls_id),
                "cls_name": str(cls_name),
                "meta": {
                    "w_px": int(w_px),
                    "h_px": int(h_px),
                    "cluster_metric": cluster_metric,
                    "brightness": float(brightness),
                },
            }
        )

    annotated_path = os.path.abspath(os.path.join(out_dir, "annotated_cluster_1.jpg"))
    cv2.imwrite(annotated_path, vis)

    csv_path = os.path.abspath(os.path.join(out_dir, "cluster_1_results.csv"))

    with open(csv_path, "w", encoding="utf-8") as f:
        f.write("filename,det_idx,cls,x1,y1,x2,y2,w_px,h_px,conf,cluster_metric,brightness\n")

        for i, d in enumerate(dets, start=1):
            x1, y1, x2, y2 = d["bbox_xyxy"]
            meta = d.get("meta", {}) or {}

            f.write(
                f"{os.path.basename(image_path)},{i},{d['cls_name']},{x1},{y1},{x2},{y2},"
                f"{meta.get('w_px', '')},{meta.get('h_px', '')},{float(d['conf']):.6f},"
                f"{meta.get('cluster_metric', '')},{meta.get('brightness', '')}\n"
            )

    total_ms = int(round((time.time() - t0) * 1000))
    inf_ms = int(round((t_inf1 - t_inf0) * 1000))

    return {
        "module_id": "cluster_1",
        "image_w": int(W),
        "image_h": int(H),
        "device_used": device_used,
        "warnings": warnings,
        "annotated_image_path": annotated_path,
        "cleaned_image_path": "",
        "artifacts": {
            "model_path": str(model_path),
            "count": int(len(dets)),
            "csv_path": csv_path,
            "brightness": brightness,
            "full_image_detections": int(full_count),
            "tiled_detections": int(tiled_count),
            "tile_sizes": [int(x) for x in CFG.get("TILE_SIZES", [])],
            "imgsz": int(TILED_IMGSZ),
            "conf": float(CFG["DET_CONF"]),
            "iou": float(CFG["DET_IOU"]),
            "nms_thr": float(CFG["DET_NMS_THR"]),
        },
        "timings_ms": {
            "total": total_ms,
            "preprocess": 0,
            "inference": inf_ms,
            "postprocess": max(0, total_ms - inf_ms),
        },
        "detections": dets,
    }