# -*- coding: utf-8 -*-
"""Claster_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNtUeYrHLXFjEL9aU-lFrAL7JCp4beEQ
"""

# Пока не всю машину распознает, а надо всю!

# ГОТОВ К ПЕРЕНОСУ

# УСТАНОВКА

# Применение: если использовать кластерность, то можно, например, обнаружить расположение двигателя, бака и так далее!

!pip -q install ultralytics==8.3.39 opencv-python-headless pillow matplotlib

import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
from ultralytics import YOLO
from google.colab import files

# классы машин COCO: car, motorcycle, bus, truck
CAR_CLASSES = {2, 3, 5, 7}

TILE_SIZE = 640
OVERLAP = 0.2
CONF_THRES = 0.25
IOU_THR = 0.2

# Порог крупности машины по доле площади кадра
AREA_FRAC_BIG = 0.10          # 10 % площади кадра

# Самую большую машину всегда дорабатываем тайлами
LARGEST_FORCE_REFINEMENT = True

# Область (ROI) вокруг машины для тайлов
ROI_SCALE = 2.0               # во сколько раз ширина/высота бокса растёт для ROI
ROI_MIN_SIZE = TILE_SIZE      # ROI не меньше 640x640

# Фильтрация кандидатов (те же машины) при дообработке
CAND_IOU_MIN = 0.10           # минимальный IoU с исходным боксом
CENTER_SCALE_X = 1.2          # допустимый сдвиг центра по X (в ширинах исходного бокса)
CENTER_SCALE_Y = 1.5          # допустимый сдвиг центра по Y (в высотах исходного бокса)

# Поджатие финального бокса, чтобы убрать лишние пустоты
SHRINK_FRAC = 0


# Поджатие финального бокса, чтобы убрать лишние пустоты
model = YOLO("yolo11n.pt")


def load_image_from_upload():
    uploaded = files.upload()
    fname = next(iter(uploaded.keys()))
    img = Image.open(fname).convert("RGB")
    img_np = np.array(img)
    img_bgr = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    return fname, img_bgr


def detect_cars_full(image, conf_thres=CONF_THRES):
    """Обычное распознавание по всему изображению без тайлов."""
    results = model.predict(image, imgsz=TILE_SIZE, conf=conf_thres, verbose=False)
    r = results[0]
    boxes = []

    if r.boxes is None or len(r.boxes) == 0:
        return boxes

    H, W = image.shape[:2]

    for b in r.boxes:
        cls_id = int(b.cls[0])
        if cls_id not in CAR_CLASSES:
            continue

        x1, y1, x2, y2 = b.xyxy[0].tolist()
        conf = float(b.conf[0])

        x1 = max(0, min(W - 1, x1))
        y1 = max(0, min(H - 1, y1))
        x2 = max(0, min(W - 1, x2))
        y2 = max(0, min(H - 1, y2))

        boxes.append([x1, y1, x2, y2, conf, cls_id])

    return boxes


def tile_image(image, tile_size=TILE_SIZE, overlap=OVERLAP):
    """Нарезка переданного изображения на тайлы. Для патча меньше 640×640 тайлов нет."""
    h, w = image.shape[:2]

    if h <= tile_size and w <= tile_size:
        return [(0, 0, image)]

    step = int(tile_size * (1.0 - overlap))
    step = max(1, step)

    tiles = []
    for y in range(0, max(h - tile_size, 0) + 1, step):
        for x in range(0, max(w - tile_size, 0) + 1, step):
            x2 = x + tile_size
            y2 = y + tile_size
            tile = image[y:y2, x:x2]
            tiles.append((x, y, tile))

    # добавление правого и нижнего краёв
    if w > tile_size:
        x = w - tile_size
        x = max(0, x)
        for y in range(0, max(h - tile_size, 0) + 1, step):
            x2 = x + tile_size
            y2 = y + tile_size
            tile = image[y:y2, x:x2]
            tiles.append((x, y, tile))

    if h > tile_size:
        y = h - tile_size
        y = max(0, y)
        for x in range(0, max(w - tile_size, 0) + 1, step):
            x2 = x + tile_size
            y2 = y + tile_size
            tile = image[y:y2, x:x2]
            tiles.append((x, y, tile))

    uniq = {}
    for x0, y0, t in tiles:
        uniq[(x0, y0)] = t
    tiles = [(x0, y0, t) for (x0, y0), t in uniq.items()]

    return tiles


def bbox_iou(box_a, box_b):
    ax1, ay1, ax2, ay2 = box_a[:4]
    bx1, by1, bx2, by2 = box_b[:4]

    ix1 = max(ax1, bx1)
    iy1 = max(ay1, by1)
    ix2 = min(ax2, bx2)
    iy2 = min(ay2, by2)

    iw = max(0.0, ix2 - ix1)
    ih = max(0.0, iy2 - iy1)
    inter = iw * ih
    if inter <= 0:
        return 0.0

    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - inter
    if union <= 0:
        return 0.0

    return inter / union
def expand_xyxy(box, frac, W, H):
    x1, y1, x2, y2 = box[:4]
    w = max(1.0, x2 - x1)
    h = max(1.0, y2 - y1)
    dx = frac * w
    dy = frac * h
    x1 = max(0.0, x1 - dx)
    y1 = max(0.0, y1 - dy)
    x2 = min(float(W - 1), x2 + dx)
    y2 = min(float(H - 1), y2 + dy)
    return [x1, y1, x2, y2]

def interval_gap(a1, a2, b1, b2):
    if a2 < b1:
        return b1 - a2
    if b2 < a1:
        return a1 - b2
    return 0.0

def axis_overlap_ratio(a1, a2, b1, b2):
    ov = max(0.0, min(a2, b2) - max(a1, b1))
    denom = max(1e-6, min(a2 - a1, b2 - b1))
    return ov / denom



def cluster_boxes_iou(boxes, iou_thr=IOU_THR):
    """Группировка боксов по IoU, одна группа = одна машина (для тайловой обработки)."""
    if not boxes:
        return []

    n = len(boxes)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i in range(n):
        for j in range(i + 1, n):
            if boxes[i][5] != boxes[j][5]:
                continue
            if bbox_iou(boxes[i], boxes[j]) >= iou_thr:
                union(i, j)

    clusters = {}
    for idx in range(n):
        root = find(idx)
        clusters.setdefault(root, []).append(idx)

    merged = []
    for comp in clusters.values():
        xs1 = [boxes[i][0] for i in comp]
        ys1 = [boxes[i][1] for i in comp]
        xs2 = [boxes[i][2] for i in comp]
        ys2 = [boxes[i][3] for i in comp]
        confs = [boxes[i][4] for i in comp]
        cls_id = boxes[comp[0]][5]

        x1 = min(xs1)
        y1 = min(ys1)
        x2 = max(xs2)
        y2 = max(ys2)
        conf = max(confs)

        merged.append([x1, y1, x2, y2, conf, cls_id])

    return merged


def detect_cars_on_tiles_whole(image):
    """Тайловая детекция по всему изображению (используется только как запасной вариант)."""
    H, W = image.shape[:2]
    tiles = tile_image(image)
    all_boxes = []

    for x0, y0, tile in tiles:
        results = model.predict(tile, imgsz=TILE_SIZE, conf=CONF_THRES, verbose=False)
        r = results[0]
        if r.boxes is None or len(r.boxes) == 0:
            continue

        for b in r.boxes:
            cls_id = int(b.cls[0])
            if cls_id not in CAR_CLASSES:
                continue

            x1, y1, x2, y2 = b.xyxy[0].tolist()
            conf = float(b.conf[0])

            gx1 = x0 + x1
            gy1 = y0 + y1
            gx2 = x0 + x2
            gy2 = y0 + y2

            gx1 = max(0, min(W - 1, gx1))
            gy1 = max(0, min(H - 1, gy1))
            gx2 = max(0, min(W - 1, gx2))
            gy2 = max(0, min(H - 1, gy2))

            all_boxes.append([gx1, gy1, gx2, gy2, conf, cls_id])

    return cluster_boxes_iou(all_boxes)



def draw_cars(image, boxes, clustered_indices=None):
    """
    image             – исходное изображение.
    boxes             – список боксов [x1, y1, x2, y2, conf, cls_id].
    clustered_indices – множество номеров машин (1-based), которые
                        были доуточнены кластерно (через тайлы).
    """
    if clustered_indices is None:
        clustered_indices = set()

    img_vis = image.copy()
    H, W = img_vis.shape[:2]

    sizes = []

    for idx, b in enumerate(boxes, start=1):
        x1, y1, x2, y2, conf, cls_id = b

        x1 = int(max(0, min(W - 1, x1)))
        y1 = int(max(0, min(H - 1, y1)))
        x2 = int(max(0, min(W - 1, x2)))
        y2 = int(max(0, min(H - 1, y2)))

        w = x2 - x1
        h = y2 - y1
        sizes.append((idx, w, h))

        # подпись на изображении – только номер и размеры
        label = f"#{idx}: {w}x{h}"
        cv2.rectangle(img_vis, (x1, y1), (x2, y2), (0, 255, 0), 3)
        cv2.putText(
            img_vis,
            label,
            (x1, max(0, y1 - 10)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
            lineType=cv2.LINE_AA
        )

    img_rgb = cv2.cvtColor(img_vis, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(10, 8))
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.show()

    if not sizes:
        print("Машины не найдены.")
        return

    print("Размеры машин (номер, ширина, высота):")
    for idx, w, h in sizes:
        if idx in clustered_indices:
            # кластерная машина – буква Т в номере
            print(f"  #{idx}Т: {w} x {h} пикселей")
        else:
            print(f"  #{idx}: {w} x {h} пикселей")



def refine_car_with_tiles_whole(image, base_box):
    """
    Уточняет бокс одной машины тайлами, но:
    - работает в ROI вокруг base_box (использует ROI_SCALE / ROI_MIN_SIZE),
    - принимает кандидаты даже без IoU с base_box (склейка по осевому перекрытию + допустимому gap),
    - склеивает части машины не только IoU'ом (иначе перед/зад не объединятся).
    """
    H, W = image.shape[:2]
    x1_b, y1_b, x2_b, y2_b = base_box

    x1_b = max(0.0, min(float(W - 1), x1_b))
    y1_b = max(0.0, min(float(H - 1), y1_b))
    x2_b = max(0.0, min(float(W - 1), x2_b))
    y2_b = max(0.0, min(float(H - 1), y2_b))

    w_b = x2_b - x1_b
    h_b = y2_b - y1_b
    if w_b <= 1 or h_b <= 1:
        return [x1_b, y1_b, x2_b, y2_b]

    cx_b = 0.5 * (x1_b + x2_b)
    cy_b = 0.5 * (y1_b + y2_b)

    # --- ROI вокруг машины ---
    roi_w = max(float(ROI_MIN_SIZE), float(ROI_SCALE) * w_b)
    roi_h = max(float(ROI_MIN_SIZE), float(ROI_SCALE) * h_b)

    rx1 = cx_b - 0.5 * roi_w
    ry1 = cy_b - 0.5 * roi_h
    rx2 = cx_b + 0.5 * roi_w
    ry2 = cy_b + 0.5 * roi_h

    rx1 = int(max(0.0, min(float(W - 1), rx1)))
    ry1 = int(max(0.0, min(float(H - 1), ry1)))
    rx2 = int(max(0.0, min(float(W - 1), rx2)))
    ry2 = int(max(0.0, min(float(H - 1), ry2)))

    if rx2 - rx1 <= 1 or ry2 - ry1 <= 1:
        return [x1_b, y1_b, x2_b, y2_b]

    roi = image[ry1:ry2, rx1:rx2]

    # расширенный базовый бокс (чтобы не отбрасывать “края”)
    base_exp = expand_xyxy([x1_b, y1_b, x2_b, y2_b], 0.25, W, H)

    # лимиты смещения центра (используем Ваши CENTER_SCALE_X/Y)
    dx_lim = 0.5 * float(CENTER_SCALE_X) * w_b
    dy_lim = 0.5 * float(CENTER_SCALE_Y) * h_b

    tiles = tile_image(roi, tile_size=TILE_SIZE, overlap=OVERLAP)

    candidates = []

    # пороги склейки частей (локально, чтобы не ломать остальную программу)
    MERGE_EXP_FRAC = 0.25
    MERGE_EXP_IOU  = 0.05
    MERGE_AXIS_OV  = 0.60
    MERGE_GAP_FRAC = 0.35

    # --- собираем кандидатов из тайлов в ROI ---
    for x0, y0, tile in tiles:
        results = model.predict(tile, imgsz=TILE_SIZE, conf=CONF_THRES, verbose=False)
        r = results[0]
        if r.boxes is None or len(r.boxes) == 0:
            continue

        for b in r.boxes:
            cls_id = int(b.cls[0])
            if cls_id not in CAR_CLASSES:
                continue

            x1, y1, x2, y2 = b.xyxy[0].tolist()

            gx1 = rx1 + x0 + x1
            gy1 = ry1 + y0 + y1
            gx2 = rx1 + x0 + x2
            gy2 = ry1 + y0 + y2

            gx1 = max(0.0, min(float(W - 1), gx1))
            gy1 = max(0.0, min(float(H - 1), gy1))
            gx2 = max(0.0, min(float(W - 1), gx2))
            gy2 = max(0.0, min(float(H - 1), gy2))

            if gx2 <= gx1 + 1 or gy2 <= gy1 + 1:
                continue

            cand = [gx1, gy1, gx2, gy2]

            # центр кандидата
            cx_c = 0.5 * (gx1 + gx2)
            cy_c = 0.5 * (gy1 + gy2)

            if abs(cx_c - cx_b) > dx_lim:
                continue
            if abs(cy_c - cy_b) > dy_lim:
                continue

            w_c = gx2 - gx1
            h_c = gy2 - gy1

            # мягкий отсев “мусора”
            if (w_c < 0.20 * w_b) and (h_c < 0.20 * h_b):
                continue
            if (w_c > 3.00 * w_b) or (h_c > 3.00 * h_b):
                continue

            iou_base = bbox_iou(cand, [x1_b, y1_b, x2_b, y2_b])
            iou_exp  = bbox_iou(cand, base_exp)

            # если IoU почти нет, всё равно берём “перед/зад” по осевому правилу
            y_ov = axis_overlap_ratio(cand[1], cand[3], base_exp[1], base_exp[3])
            x_ov = axis_overlap_ratio(cand[0], cand[2], base_exp[0], base_exp[2])

            x_gap = interval_gap(cand[0], cand[2], base_exp[0], base_exp[2])
            y_gap = interval_gap(cand[1], cand[3], base_exp[1], base_exp[3])

            ok = False
            if iou_base >= CAND_IOU_MIN or iou_exp >= max(0.02, 0.5 * CAND_IOU_MIN):
                ok = True
            elif (y_ov >= 0.60) and (x_gap <= 0.40 * max(w_b, w_c)):
                ok = True
            elif (x_ov >= 0.60) and (y_gap <= 0.40 * max(h_b, h_c)):
                ok = True

            if ok:
                candidates.append(cand)

    if not candidates:
        return [x1_b, y1_b, x2_b, y2_b]

    # добавляем базовый бокс как якорь
    candidates.append([x1_b, y1_b, x2_b, y2_b])
    base_idx = len(candidates) - 1

    # --- склейка кандидатов: IoU + IoU расширенных + осевое перекрытие/разрыв ---
    n = len(candidates)
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i in range(n):
        bi = candidates[i]
        wi = max(1.0, bi[2] - bi[0])
        hi = max(1.0, bi[3] - bi[1])
        ei = expand_xyxy(bi, MERGE_EXP_FRAC, W, H)

        for j in range(i + 1, n):
            bj = candidates[j]
            wj = max(1.0, bj[2] - bj[0])
            hj = max(1.0, bj[3] - bj[1])
            ej = expand_xyxy(bj, MERGE_EXP_FRAC, W, H)

            merged = False

            if bbox_iou(bi, bj) >= IOU_THR:
                merged = True
            elif bbox_iou(ei, ej) >= MERGE_EXP_IOU:
                merged = True
            else:
                y_ov = axis_overlap_ratio(bi[1], bi[3], bj[1], bj[3])
                x_ov = axis_overlap_ratio(bi[0], bi[2], bj[0], bj[2])

                x_gap = interval_gap(bi[0], bi[2], bj[0], bj[2])
                y_gap = interval_gap(bi[1], bi[3], bj[1], bj[3])

                if (y_ov >= MERGE_AXIS_OV) and (x_gap <= MERGE_GAP_FRAC * max(wi, wj)):
                    merged = True
                elif (x_ov >= MERGE_AXIS_OV) and (y_gap <= MERGE_GAP_FRAC * max(hi, hj)):
                    merged = True

            if merged:
                union(i, j)

    root_base = find(base_idx)
    group = [candidates[i] for i in range(n) if find(i) == root_base]

    if not group:
        return [x1_b, y1_b, x2_b, y2_b]

    xs1 = [b[0] for b in group]
    ys1 = [b[1] for b in group]
    xs2 = [b[2] for b in group]
    ys2 = [b[3] for b in group]

    x1_new = max(0.0, min(xs1))
    y1_new = max(0.0, min(ys1))
    x2_new = min(float(W - 1), max(xs2))
    y2_new = min(float(H - 1), max(ys2))

    if SHRINK_FRAC > 0.0:
        w_new = max(1.0, x2_new - x1_new)
        h_new = max(1.0, y2_new - y1_new)
        dx = float(SHRINK_FRAC) * w_new
        dy = float(SHRINK_FRAC) * h_new
        x1_new = max(0.0, x1_new + dx)
        y1_new = max(0.0, y1_new + dy)
        x2_new = min(float(W - 1), x2_new - dx)
        y2_new = min(float(H - 1), y2_new - dy)

    return [int(x1_new), int(y1_new), int(x2_new), int(y2_new)]


def process_image():
    fname, img = load_image_from_upload()
    H, W = img.shape[:2]
    print("Файл:", fname)
    print("Размер изображения (W x H):", W, "x", H)

    # 1. Обычная детекция
    full_boxes = detect_cars_full(img)
    print("Найдено машин обычным способом:", len(full_boxes))

    # 2. Если вообще никого не нашли → тайлы по всему кадру
    if not full_boxes:
        print("Обычная детекция не нашла машин, включается тайловый режим по всему кадру.")
        tiled_boxes = detect_cars_on_tiles_whole(img)
        draw_cars(img, tiled_boxes)
        return

    # 3. Если всё изображение помещается в 640×640 → кластеризация НЕ нужна
    if W <= TILE_SIZE and H <= TILE_SIZE:
        draw_cars(img, full_boxes)
        return

    # 4. Основная логика — кластеры только если БОКС машины больше тайла
    final_boxes = []
    clustered_indices = set()

    for idx, b in enumerate(full_boxes):
        x1, y1, x2, y2, conf, cls_id = b
        w = x2 - x1
        h = y2 - y1

        # условие: машина слишком крупная, не помещается в один 640×640
        need_cluster = (w > TILE_SIZE or h > TILE_SIZE)

        if need_cluster:
            # уточняем кластеризацией по всем тайлам кадра
            nx1, ny1, nx2, ny2 = refine_car_with_tiles_whole(img, [x1, y1, x2, y2])
            final_boxes.append([nx1, ny1, nx2, ny2, conf, cls_id])
            clustered_indices.add(idx + 1)
        else:
            # машина помещается в тайл → оставляем как есть
            final_boxes.append(b)

    # 5. Отрисовка + вывод размеров
    draw_cars(img, final_boxes, clustered_indices)
    return

# ЗАПУСК
process_image()