# -*- coding: utf-8 -*-
"""Objects_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cC7BFFLQokQhHUg3SPom5I782ZluFPXo
"""


# Импорты
import os  # Работа с файловой системой
import numpy as np  # Массивы и математика
try:
    import pyheif
except Exception:
    pyheif = None

try:
    import matplotlib.pyplot as plt
except Exception:
    plt = None  # Чтение HEIC-файлов (iPhone)
import cv2  # OpenCV: компьютерное зрение
from PIL import Image, ExifTags  # PIL: изображения и EXIF-теги
from ultralytics import YOLO  # Модель YOLO от ultralytics

# Google Drive (Colab)
try:
    from google.colab import drive
except Exception:
    drive = None
GDRIVE = False

# Пути
if GDRIVE:  # Если Google Drive смонтирован
    image_dir = "/content/gdrive/MyDrive/DRONE/foto"  # Папка с исходными фото на Google Drive
    save_dir = "/content/gdrive/MyDrive/DRONE/save"  # Папка для результатов и CSV
else:  # Если работаем локально
    image_dir = "./foto"  # Локальная папка с фото
    save_dir = "./save"  # Локальная папка для результатов
os.makedirs(save_dir, exist_ok=True)  # Создаём папку сохранения, если её нет

# Настройка камеры
FOCAL_MM = 4.25  # Фокусное расстояние объектива (мм) для iPhone 11
SENSOR_WIDTH_MM = 5.6  # Оценка ширины матрицы (мм), нужна для перевода фокусного в пиксели

# Габариты ТС (ширина, высота, длина) в метрах
VEHICLE_DIMENSIONS = {  # Типичные размеры транспортных средств
    "car": (1.8, 1.5, 4.5),  # Легковой автомобиль
    "truck": (2.5, 3.0, 9.0),  # Грузовик
    "bus": (2.5, 3.2, 12.0),  # Автобус
    "motorcycle": (0.8, 1.2, 2.1),  # Мотоцикл
    "default": (1.85, 1.5, 4.5)  # Значения по умолчанию
}

# CSV
csv_path = os.path.join(save_dir, "detections.csv")  # Путь к CSV с результатами детекции
with open(csv_path, 'w', newline='') as f:  # Открываем CSV на перезапись
    f.write("Image,ID,Class,x1,y1,x2,y2,Width,Height,Confidence,Distance(m),Brightness\n")  # Заголовки столбцов

# EXIF CSV
merged_exif_path = os.path.join(save_dir, "merged_exif.csv")  # Путь к CSV с EXIF всех фотографий

# Вспомогательные функции
def get_exif_focal_length(pil_img):  # Получение фокусного расстояния из EXIF
    try:
        exif_data = pil_img._getexif()  # Сырые EXIF-данные
        if exif_data is None:  # Если EXIF нет
            return FOCAL_MM  # Возвращаем значение по умолчанию
        for tag_id, value in exif_data.items():  # Перебор всех тегов EXIF
            tag = ExifTags.TAGS.get(tag_id, tag_id)  # Преобразование ID тега в имя
            if tag == 'FocalLength':  # Ищем тег фокусного расстояния
                return value[0] / value[1] if isinstance(value, tuple) else float(value)  # Преобразуем к float
        return FOCAL_MM  # Если нужный тег не найден
    except Exception:
        return FOCAL_MM  # При ошибке возвращаем значение по умолчанию

def estimate_focal_pixels(focal_mm, sensor_width_mm, image_width_px):  # Перевод фокусного из мм в пиксели
    return (focal_mm / sensor_width_mm) * image_width_px  # Формула: f_pix = f_mm / sensor_width * width_px

def estimate_brightness(image_bgr):  # Оценка средней яркости кадра
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)  # Перевод в градации серого
    return round(float(np.mean(gray)), 2)  # Среднее значение яркости по всем пикселям

# Модель
model = YOLO("yolov8m.pt")  # Загрузка предобученной модели YOLO v8m (COCO)

YOLO_IMGSZ = 1280  # Размер входного изображения для YOLO
YOLO_CONF_GLOBAL = 0.15  # Глобальный минимальный порог уверенности для детекции
SCALE_TINY_MAX = 0.02  # Максимальная относительная высота для tiny-объектов (2% от высоты кадра)
SCALE_SMALL_MAX = 0.05  # Максимальная относительная высота для small-объектов (5% от высоты кадра)
MIN_BOX_TINY = 10  # Минимальный размер бокса (пиксели) для tiny-объектов
MIN_BOX_SMALL = 20  # Минимальный размер бокса для small-объектов
MIN_BOX_NORMAL = 30  # Минимальный размер бокса для нормальных/крупных объектов
CONF_TINY = 0.18  # Требуемая уверенность для tiny-боксов
CONF_SMALL = 0.22  # Требуемая уверенность для small-боксов
CONF_NORMAL = 0.28  # Требуемая уверенность для нормальных боксов

VEHICLE_CLASSES = {"car", "truck", "bus", "motorcycle"}  # Классы, которые считаем транспортом
if __name__ == "__main__":
    # Обработка изображений
    valid_ext = (".heic", ".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp")  # Допустимые расширения файлов изображений
    filenames = sorted([f for f in os.listdir(image_dir) if f.lower().endswith(valid_ext)])  # Отфильтрованный и отсортированный список файлов

    for filename in filenames:  # Основной цикл по файлам
        image_path = os.path.join(image_dir, filename)  # Полный путь к изображению
        print(f"[INFO] {filename}")  # Лог: имя обрабатываемого файла

        # EXIF -> merged_exif.csv
        if not os.path.exists(merged_exif_path):  # Если файла с EXIF ещё нет
            os.system(f'exiftool -csv "{image_path}" > "{merged_exif_path}"')  # Создаём CSV и пишем в него EXIF текущего файла
        else:
            os.system(f'exiftool -csv "{image_path}" | tail -n +2 >> "{merged_exif_path}"')  # Добавляем EXIF без заголовка

        # Загрузка изображения
        try:
            if filename.lower().endswith(".heic"):  # Если формат HEIC
                heif = pyheif.read(image_path)  # Читаем HEIC с помощью pyheif
                image_pil = Image.frombytes(heif.mode, heif.size, heif.data, "raw", heif.mode)  # Создаём PIL-изображение
            else:
                image_pil = Image.open(image_path).convert("RGB")  # Открываем обычный формат и приводим к RGB

            img = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2BGR)  # Преобразуем изображение в формат BGR для OpenCV
        except Exception as e:
            print(f"[ERROR] load: {e}")  # Логируем ошибку загрузки
            continue  # Переходим к следующему файлу

        H, W = img.shape[:2]  # Высота и ширина изображения в пикселях
        brightness = estimate_brightness(img)  # Средняя яркость кадра
        focal_mm = get_exif_focal_length(image_pil)  # Фокусное расстояние из EXIF (либо значение по умолчанию)
        focal_px = estimate_focal_pixels(focal_mm, SENSOR_WIDTH_MM, W)  # Фокусное расстояние в пикселях

        result = model(  # Запуск модели YOLO
            img,  # Входное изображение
            imgsz=YOLO_IMGSZ,  # Размер для ресайза внутри модели
            conf=YOLO_CONF_GLOBAL,  # Глобальный порог уверенности
            verbose=False  # Без лишнего вывода
        )[0]  # Берём первый результат из списка

        names = getattr(result, "names", None) or getattr(getattr(model, "model", None), "names", {}) or {}  # Словарь ID класса -> имя

        det_idx = 0  # Счётчик детекций на текущем изображении

        for box in result.boxes:  # Цикл по всем найденным боксам
            conf = float(box.conf[0])  # Уверенность данной детекции

            x1, y1, x2, y2 = map(int, box.xyxy[0])  # Координаты бокса (левый верхний и правый нижний углы)
            w_px = x2 - x1  # Ширина бокса в пикселях
            h_px = y2 - y1  # Высота бокса в пикселях

            rel_h = h_px / max(H, 1)  # Относительная высота бокса (доля от высоты всего изображения)

            if rel_h <= SCALE_TINY_MAX:  # Tiny-объект (очень маленький)
                min_box_side = MIN_BOX_TINY  # Минимальный размер бокса для tiny
                conf_required = CONF_TINY  # Нужная уверенность для tiny
            elif rel_h <= SCALE_SMALL_MAX:  # Small-объект
                min_box_side = MIN_BOX_SMALL  # Минимальный размер бокса для small
                conf_required = CONF_SMALL  # Нужная уверенность для small
            else:  # Нормальный или крупный объект
                min_box_side = MIN_BOX_NORMAL  # Минимальный размер бокса для normal
                conf_required = CONF_NORMAL  # Нужная уверенность для normal

            if w_px < min_box_side or h_px < min_box_side:  # Если бокс меньше допустимого размера
                continue  # Отбрасываем
            if conf < conf_required:  # Если уверенность ниже порога для текущего масштаба
                continue  # Отбрасываем

            class_id = int(box.cls[0])  # ID класса
            cls = names.get(class_id, "default")  # Имя класса по ID

            if cls not in VEHICLE_CLASSES:  # Если класс не из набора транспортных
                continue  # Пропускаем

            _, real_h, _ = VEHICLE_DIMENSIONS.get(cls, VEHICLE_DIMENSIONS["default"])  # Реальная высота ТС (м)
            dist = round(focal_px * real_h / max(h_px, 1), 2)  # Оценка расстояния до объекта по формуле линзы
            det_idx += 1  # Увеличиваем номер детекции

            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)  # Рисуем зелёный прямоугольник вокруг объекта

            label = f"{cls} {det_idx} ~{dist}m"  # Текст подписи (класс, ID, расстояние)
            pt = (x1, max(20, y1 - 10))  # Позиция подписи (чуть выше рамки)
            font = cv2.FONT_HERSHEY_SIMPLEX  # Тип шрифта
            cv2.putText(img, label, pt, font, 0.8, (0, 0, 0), 5, cv2.LINE_AA)  # Чёрная подложка текста (толстый контур)
            cv2.putText(img, label, pt, font, 0.8, (255, 255, 255), 2, cv2.LINE_AA)  # Белый текст поверх

            row = [  # Строка для CSV по одной детекции
                filename, det_idx, cls, x1, y1, x2, y2, w_px, h_px,
                round(conf, 2), dist, brightness
            ]
            with open(csv_path, 'a', newline='') as f:  # Открываем CSV в режиме добавления
                f.write(",".join(map(str, row)) + "\n")  # Записываем строку

        # Сохранение и показ
        out_path = os.path.join(save_dir, f"result_{os.path.splitext(filename)[0]}.jpg")  # Путь для сохранения изображения с рамками
        cv2.imwrite(out_path, img)  # Сохраняем обработанное изображение
        plt.figure(figsize=(20, 12))  # Создаём фигуру для отображения
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  # Конвертируем BGR -> RGB и показываем
        plt.axis('off')  # Убираем оси
        plt.title(filename)  # Заголовок – имя файла
        plt.show()  # Отображаем изображение

    print(f"Данные для объектов: {csv_path}")  # Путь к CSV с детекциями
    print(f"Данные для фотографий EXIF: {merged_exif_path}")  # Путь к CSV с EXIF

def run(image_path: str, out_dir: str, cfg: dict, device_mode: str = "auto") -> dict:
    """
    Должна вернуть dict в формате ModuleResult:
    {
      "module_id": "...",
      "image_w": int,
      "image_h": int,
      "device_used": "gpu|cpu",
      "warnings": [..],
      "annotated_image_path": "...",
      "cleaned_image_path": "...",
      "artifacts": {...},
      "timings_ms": {...},
      "detections": [ { "bbox_xyxy":[x1,y1,x2,y2], "conf":float, "cls_id":int, "cls_name":str, "meta":{} } ]
    }
    """
    raise NotImplementedError("Замените телo run() на вызов вашей логики внутри этого файла и сбор результата в dict ModuleResult")