# -*- coding: utf-8 -*-
"""Rotation_detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjaWH214N4NvDg7NiFbxqeHgUwz3VzyR
"""


import math, json, os, time
import numpy as np
import cv2
import os
import time

try:
    import torch
except Exception:
    torch = None

try:
    import pandas as pd
except Exception:
    pd = None

try:
    import matplotlib.pyplot as plt
except Exception:
    plt = None

from ultralytics import YOLO

try:
    from google.colab import files
except Exception:
    files = None

from PIL import Image, ImageOps
from io import BytesIO

try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except Exception:
    pillow_heif = None

try:
    import torch
except Exception:
    torch = None

CAR_CLASSES = {2, 3, 5, 7}

# Чтение любого изображения (JPEG/PNG/HEIC)
def read_image_auto(file_bytes: bytes):
    arr = np.frombuffer(file_bytes, np.uint8)
    img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img is not None:
        return img
    try:
        pil = Image.open(BytesIO(file_bytes))
        pil = ImageOps.exif_transpose(pil).convert("RGB")
        return cv2.cvtColor(np.array(pil), cv2.COLOR_RGB2BGR)
    except Exception as e:
        print("HEIC read error:", repr(e))
        return None

def read_image_path(image_path: str):
    with open(image_path, "rb") as f:
        data = f.read()
    return read_image_auto(data)


# Детектор машин (YOLOv11l + тайлинг + NMS)

yolo = YOLO("yolo11n.pt")

# model = YOLO("yolo11n.pt")   # nano
# model = YOLO("yolo11s.pt")   # small
# model = YOLO("yolo11m.pt")   # medium
# model = YOLO("yolo11l.pt")   # large
# model = YOLO("yolo11x.pt")   # x-large

YOLO_DEVICE_ARG = None

def rotate_bound(img_bgr: np.ndarray, angle_deg: float):
    """
    Поворот без обрезания краёв (expand). Возвращает:
    rotated_bgr, M3 (3x3), Minv (3x3)
    """
    h, w = img_bgr.shape[:2]
    cx, cy = w / 2.0, h / 2.0

    M = cv2.getRotationMatrix2D((cx, cy), angle_deg, 1.0)  # 2x3
    cos = abs(M[0, 0])
    sin = abs(M[0, 1])

    new_w = int(h * sin + w * cos)
    new_h = int(h * cos + w * sin)

    M[0, 2] += new_w / 2.0 - cx
    M[1, 2] += new_h / 2.0 - cy

    rotated = cv2.warpAffine(img_bgr, M, (new_w, new_h), flags=cv2.INTER_LINEAR)

    M3 = np.array([[M[0, 0], M[0, 1], M[0, 2]],
                   [M[1, 0], M[1, 1], M[1, 2]],
                   [0.0,     0.0,     1.0]], dtype=np.float64)
    Minv = np.linalg.inv(M3)
    return rotated, M3, Minv

def estimate_true_image_rotation_deg(img_bgr: np.ndarray) -> float:
    """
    Оценка непрерывного угла наклона сцены (любой градус: 1, 33, 52.6, 359.9).
    Возвращает угол поворота (в градусах), который нужно ПРИМЕНИТЬ к изображению,
    чтобы доминирующие линии сцены стали ближе к горизонтали/вертикали.
    """
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

    h, w = gray.shape[:2]
    max_side = max(h, w)
    scale = 1.0
    if max_side > 1400:
        scale = 1400.0 / max_side
        gray = cv2.resize(gray, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)

    lsd = cv2.createLineSegmentDetector(cv2.LSD_REFINE_STD)
    lines = lsd.detect(gray)[0]

    if lines is None or len(lines) < 12:
        edges = cv2.Canny(gray, 60, 180)
        hough = cv2.HoughLinesP(edges, 1, np.pi / 180.0, threshold=80,
                                minLineLength=60, maxLineGap=10)
        if hough is None or len(hough) < 12:
            return 0.0
        lines = hough.astype(np.float32).reshape(-1, 1, 4)

    angles = []
    weights = []

    for x1, y1, x2, y2 in lines.reshape(-1, 4):
        dx = float(x2 - x1)
        dy = float(y2 - y1)
        length = math.hypot(dx, dy)
        if length < 45.0:
            continue
        ang = math.degrees(math.atan2(dy, dx))  # [-180..180]
        ang = ang % 180.0                       # [0..180)
        angles.append(ang)
        weights.append(length)

    if len(angles) < 12:
        return 0.0

    a = np.deg2rad(np.array(angles, dtype=np.float64))
    wts = np.array(weights, dtype=np.float64)

    c = np.cos(2.0 * a)
    s = np.sin(2.0 * a)
    mean2 = math.atan2(float(np.sum(s * wts)), float(np.sum(c * wts)))
    dom = 0.5 * mean2
    dom_deg = (math.degrees(dom)) % 180.0

    # Поворачиваем к ближайшей оси (0 или 90), но угол остаётся непрерывным
    target = 90.0 if abs(dom_deg - 90.0) < abs(dom_deg - 0.0) else 0.0
    rot = target - dom_deg

    return rot % 360.0

def normalize_scene_single_pass(img_bgr: np.ndarray):
    """
    ЕДИНСТВЕННЫЙ проход нормализации сцены:
    - вычисляет непрерывный угол
    - строит R_img (выровненное изображение)
    Возвращает: R_img, rot_deg, M3, Minv
    """
    rot_deg = estimate_true_image_rotation_deg(img_bgr)
    R_img, M3, Minv = rotate_bound(img_bgr, rot_deg)
    return R_img, rot_deg, M3, Minv

def iou_xyxy(a, b):
    ax1, ay1, ax2, ay2 = a; bx1, by1, bx2, by2 = b
    ix1, iy1 = max(ax1,bx1), max(ay1,by1)
    ix2, iy2 = min(ax2,bx2), min(ay2,by2)
    iw, ih = max(0, ix2-ix1), max(0, iy2-iy1)
    inter = iw*ih
    au = max(0,ax2-ax1)*max(0,ay2-ay1)
    bu = max(0,bx2-bx1)*max(0,by2-by1)
    return inter / (au + bu - inter + 1e-6)

def nms_union(boxes, thr=0.55):
    boxes = sorted(boxes, key=lambda x: x[4], reverse=True)
    kept=[]
    for b in boxes:
        if all(iou_xyxy(b[:4], k[:4]) <= thr for k in kept):
            kept.append(b)
    return kept

def merge_close_small(boxes, max_dist=6, max_size=26):
    """
    Склейка пачек очень мелких боксов, которые
    сидят почти в одной точке (типичная россыпь шума вдали).
    """
    small = []
    big = []
    for b in boxes:
        x1, y1, x2, y2, c = b
        w = x2 - x1
        h = y2 - y1
        if min(w, h) <= max_size:
            small.append(b)
        else:
            big.append(b)

    used = [False] * len(small)
    merged_small = []

    for i, b in enumerate(small):
        if used[i]:
            continue
        x1, y1, x2, y2, c = b
        cx = 0.5 * (x1 + x2)
        cy = 0.5 * (y1 + y2)

        group = [b]
        used[i] = True

        for j in range(i + 1, len(small)):
            if used[j]:
                continue
            x1b, y1b, x2b, y2b, cb = small[j]
            cxb = 0.5 * (x1b + x2b)
            cyb = 0.5 * (y1b + y2b)

            if abs(cxb - cx) <= max_dist and abs(cyb - cy) <= max_dist:
                group.append(small[j])
                used[j] = True

        xs1 = [g[0] for g in group]
        ys1 = [g[1] for g in group]
        xs2 = [g[2] for g in group]
        ys2 = [g[3] for g in group]
        conf = max(g[4] for g in group)

        merged_small.append((
            min(xs1),
            min(ys1),
            max(xs2),
            max(ys2),
            conf
        ))

    return big + merged_small


def filter_boxes_geom(boxes):
    """
    Отсев откровенного мусора по геометрии и уверенности
    без отрезания дальних машин по расстоянию.
    """
    filtered = []

    for (x1, y1, x2, y2, c) in boxes:
        w = x2 - x1
        h = y2 - y1
        if w <= 0 or h <= 0:
            continue

        s = min(w, h)
        ar = w / float(h)

        # совсем микроскопический бокс – ни ориентацию, ни расстояние не посчитать
        if s < 5:
            continue

        # слишком вытянутые: столбы, барьеры, части разметки
        if ar < 0.25 or ar > 5.0:
            continue

        # адаптивный порог по размеру:
        # чем меньше бокс, тем выше требование к conf
        if s < 10 and c < 0.25:
            continue
        if 10 <= s < 20 and c < 0.15:
            continue
        if s >= 20 and c < 0.08:
            continue

        filtered.append((x1, y1, x2, y2, c))

    # склейка россыпи мелких дублей в дальней зоне
    filtered = merge_close_small(filtered)

    return filtered

# Повороты и маппинг координат
def rotate_k90_bgr(img_bgr: np.ndarray, k: int) -> np.ndarray:
    k %= 4
    if k == 0:
        return img_bgr
    if k == 1:
        return cv2.rotate(img_bgr, cv2.ROTATE_90_CLOCKWISE)
    if k == 2:
        return cv2.rotate(img_bgr, cv2.ROTATE_180)
    return cv2.rotate(img_bgr, cv2.ROTATE_90_COUNTERCLOCKWISE)

def _rotate_point_k90(x: float, y: float, W: int, H: int, k: int):
    k %= 4
    if k == 0:
        return x, y, W, H
    if k == 1:  # CW
        return (H - 1 - y), x, H, W
    if k == 2:
        return (W - 1 - x), (H - 1 - y), W, H
    # CCW
    return y, (W - 1 - x), H, W

def bbox_rotate_k90(bbox_xyxy, W: int, H: int, k: int):
    x1, y1, x2, y2 = map(float, bbox_xyxy)
    pts = [(x1, y1), (x2, y1), (x2, y2), (x1, y2)]
    rpts = []
    nW, nH = W, H
    for (x, y) in pts:
        rx, ry, nW, nH = _rotate_point_k90(x, y, W, H, k)
        rpts.append((rx, ry))
    xs = [p[0] for p in rpts]
    ys = [p[1] for p in rpts]
    return [int(round(min(xs))), int(round(min(ys))), int(round(max(xs))), int(round(max(ys)))], nW, nH

def rotate_boxes_k90_back(boxes_rot, W_base, H_base, k_applied):
    """
    boxes_rot заданы в координатах изображения, полученного поворотом base на k_applied*90 (CW).
    Возвращает боксы в координатах base.
    """
    k = int(k_applied) % 4
    if k == 0:
        return boxes_rot

    # размеры изображения после поворота base на k
    Wr, Hr = (W_base, H_base) if (k % 2 == 0) else (H_base, W_base)
    k_inv = (-k) % 4

    out = []
    for (x1, y1, x2, y2, conf) in boxes_rot:
        bb0, _, _ = bbox_rotate_k90([x1, y1, x2, y2], Wr, Hr, k_inv)
        X1, Y1, X2, Y2 = bb0

        # зажим в границы base
        X1 = max(0, min(int(X1), W_base - 1))
        X2 = max(0, min(int(X2), W_base - 1))
        Y1 = max(0, min(int(Y1), H_base - 1))
        Y2 = max(0, min(int(Y2), H_base - 1))

        if (X2 - X1) < 2 or (Y2 - Y1) < 2:
            continue

        out.append((X1, Y1, X2, Y2, float(conf)))
    return out

def _rotate_bound(img_bgr: np.ndarray, angle_deg: float):
    """
    Поворот без обрезки (увеличивает холст).
    Возвращает: (rotated_img, M, (newW,newH))
    M: 2x3 аффинная матрица original -> rotated
    """
    h, w = img_bgr.shape[:2]
    if h < 2 or w < 2:
        return img_bgr, np.array([[1,0,0],[0,1,0]], dtype=np.float32), (w, h)

    cx, cy = w / 2.0, h / 2.0
    M = cv2.getRotationMatrix2D((cx, cy), float(angle_deg), 1.0).astype(np.float32)

    cos = abs(M[0, 0])
    sin = abs(M[0, 1])

    newW = int(h * sin + w * cos)
    newH = int(h * cos + w * sin)

    # сдвиг, чтобы картинка оказалась по центру нового холста
    M[0, 2] += (newW / 2.0) - cx
    M[1, 2] += (newH / 2.0) - cy

    rot = cv2.warpAffine(
        img_bgr, M, (newW, newH),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(114,114,114)
    )
    return rot, M, (newW, newH)

def _apply_affine_to_points(M2x3: np.ndarray, pts_xy: np.ndarray):
    pts = np.asarray(pts_xy, dtype=np.float32).reshape(-1, 2)
    ones = np.ones((pts.shape[0], 1), dtype=np.float32)
    pts_h = np.hstack([pts, ones])  # Nx3
    out = (M2x3 @ pts_h.T).T        # Nx2
    return out

def _map_boxes_from_rotated_to_base(boxes_rot, M_base_to_rot, W_base, H_base):
    """
    boxes_rot: list[(x1,y1,x2,y2,conf)] в координатах rotated
    Возвращает боксы в координатах base (исходного img_bgr) как axis-aligned bbox.
    """
    if not boxes_rot:
        return []

    Minv = cv2.invertAffineTransform(np.asarray(M_base_to_rot, dtype=np.float32))
    out = []
    for (x1,y1,x2,y2,conf) in boxes_rot:
        pts = np.array([[x1,y1],[x2,y1],[x2,y2],[x1,y2]], dtype=np.float32)
        pts0 = _apply_affine_to_points(Minv, pts)
        xs = pts0[:,0]; ys = pts0[:,1]
        xx1 = int(np.floor(xs.min())); yy1 = int(np.floor(ys.min()))
        xx2 = int(np.ceil(xs.max()));  yy2 = int(np.ceil(ys.max()))

        # зажать в границы base
        xx1 = max(0, min(xx1, W_base - 1))
        yy1 = max(0, min(yy1, H_base - 1))
        xx2 = max(0, min(xx2, W_base - 1))
        yy2 = max(0, min(yy2, H_base - 1))

        if (xx2 - xx1) < 3 or (yy2 - yy1) < 3:
            continue
        out.append((xx1, yy1, xx2, yy2, float(conf)))
    return out

def _map_bbox_from_base_to_rotated(bbox_xyxy, M_base_to_rot, W_rot, H_rot):
    x1, y1, x2, y2 = map(float, bbox_xyxy)
    pts = np.array([[x1, y1], [x2, y1], [x2, y2], [x1, y2]], dtype=np.float32)
    pr = _apply_affine_to_points(np.asarray(M_base_to_rot, dtype=np.float32), pts)
    xs = pr[:, 0]; ys = pr[:, 1]

    xx1 = int(np.floor(xs.min())); yy1 = int(np.floor(ys.min()))
    xx2 = int(np.ceil(xs.max()));  yy2 = int(np.ceil(ys.max()))

    xx1 = max(0, min(xx1, W_rot - 1))
    yy1 = max(0, min(yy1, H_rot - 1))
    xx2 = max(0, min(xx2, W_rot - 1))
    yy2 = max(0, min(yy2, H_rot - 1))

    if (xx2 - xx1) < 3 or (yy2 - yy1) < 3:
        return None
    return (xx1, yy1, xx2, yy2)


def rotate_image_and_boxes_back(img, angle_deg, boxes_rot):
    """
    Поворачивает изображение и боксы обратно на заданный угол.
    Используется для возврата координат боксов после поворота изображения.
    """
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w/2, h/2), angle_deg, 1.0)
    Minv = cv2.invertAffineTransform(M)
    out = []
    for (x1,y1,x2,y2,conf) in boxes_rot:
        pts = np.array([[x1,y1],[x2,y1],[x2,y2],[x1,y2]], dtype=np.float32)
        pts = np.hstack([pts, np.ones((4,1), np.float32)])
        pts = (Minv @ pts.T).T
        xs, ys = pts[:,0], pts[:,1]
        xx1, yy1, xx2, yy2 = int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())

        # жёстко зажимаем в границах изображения
        xx1 = max(0, min(xx1, w - 1))
        yy1 = max(0, min(yy1, h - 1))
        xx2 = max(0, min(xx2, w - 1))
        yy2 = max(0, min(yy2, h - 1))

        # отсеиваем совсем крошечные боксы – от них LSD всё равно толку нет
        if xx2 - xx1 < 6 or yy2 - yy1 < 6:
            continue

        out.append((xx1, yy1, xx2, yy2, conf))
    return out

def bbox_from_work_to_original(bbox_work_xyxy, W0: int, H0: int, rot_k: int):
    # work = rotate(original, rot_k CW). Чтобы вернуть обратно -> k_inv = -rot_k
    k_inv = (-rot_k) % 4
    Wr, Hr = (W0, H0) if (rot_k % 2 == 0) else (H0, W0)
    bbox0, _, _ = bbox_rotate_k90(bbox_work_xyxy, Wr, Hr, k_inv)
    # зажмём в границы
    x1, y1, x2, y2 = bbox0
    x1 = max(0, min(x1, W0 - 1))
    x2 = max(0, min(x2, W0 - 1))
    y1 = max(0, min(y1, H0 - 1))
    y2 = max(0, min(y2, H0 - 1))
    return [x1, y1, x2, y2]

#YOLO

def _run_yolo_cars(im_bgr, conf, iou, imgsz, max_det, tta=False):
    kwargs = dict(conf=conf, iou=iou, imgsz=imgsz, max_det=max_det, verbose=False)
    if "YOLO_DEVICE_ARG" in globals() and YOLO_DEVICE_ARG is not None:
        kwargs["device"] = YOLO_DEVICE_ARG
    if tta:
        kwargs["augment"] = True

    r = yolo(im_bgr, **kwargs)[0]
    boxes = []
    for b in r.boxes:
        if int(b.cls.item()) in CAR_CLASSES:
            x1, y1, x2, y2 = b.xyxy[0].cpu().numpy().tolist()
            boxes.append((int(x1), int(y1), int(x2), int(y2), float(b.conf.item())))
    return boxes


def _estimate_deskew_angle_deg(img_bgr: np.ndarray, max_side: int = 960):
    """
    Оценка доминирующего угла линий в кадре (градусы в диапазоне [-90, 90)).
    Возвращает None, если линий мало/нет.
    """
    if img_bgr is None or img_bgr.size == 0:
        return None
    H, W = img_bgr.shape[:2]
    if H < 32 or W < 32:
        return None

    scale = 1.0
    work = img_bgr
    if max(H, W) > max_side:
        scale = max_side / float(max(H, W))
        work = cv2.resize(work, (max(2, int(W * scale)), max(2, int(H * scale))), interpolation=cv2.INTER_AREA)

    g = cv2.cvtColor(work, cv2.COLOR_BGR2GRAY)
    g = cv2.GaussianBlur(g, (5, 5), 0)

    edges = cv2.Canny(g, 50, 150)
    m = max(work.shape[:2])
    min_len = int(0.10 * m)
    lines = cv2.HoughLinesP(edges, 1, np.pi / 180.0, threshold=80, minLineLength=min_len, maxLineGap=20)
    if lines is None:
        return None

    hist = np.zeros(180, dtype=np.float32)
    for x1, y1, x2, y2 in lines.reshape(-1, 4):
        dx = float(x2 - x1)
        dy = float(y2 - y1)
        L = math.hypot(dx, dy)
        if L < 1.0:
            continue
        ang = math.degrees(math.atan2(dy, dx))
        # нормализация в [-90, 90)
        while ang >= 90.0:
            ang -= 180.0
        while ang < -90.0:
            ang += 180.0
        idx = int(round(ang + 90.0))
        idx = 0 if idx < 0 else (179 if idx > 179 else idx)
        hist[idx] += L

    if hist.max() <= 0:
        return None

    peak = int(hist.argmax())
    return float(peak - 90.0)

def _affine_to_3x3(M2x3: np.ndarray) -> np.ndarray:
    M2x3 = np.asarray(M2x3, dtype=np.float32).reshape(2, 3)
    return np.vstack([M2x3, np.array([[0.0, 0.0, 1.0]], dtype=np.float32)])

def _affine_compose(M2: np.ndarray, M1: np.ndarray) -> np.ndarray:
    """
    Композиция аффинных преобразований:
    base -> (M1) -> mid -> (M2) -> out
    Возвращает M_total: base -> out
    """
    A = _affine_to_3x3(M2)
    B = _affine_to_3x3(M1)
    C = A @ B
    return C[:2, :].astype(np.float32)

def _looks_upside_down(img_bgr: np.ndarray, frac: float = 0.22, ratio_thr: float = 1.18) -> bool:
    """
    Очень грубая эвристика для 180°:
    если низ кадра заметно ярче верха, часто это “вверх ногами”.
    """
    if img_bgr is None or img_bgr.size == 0:
        return False
    h, w = img_bgr.shape[:2]
    if h < 64 or w < 64:
        return False
    k = max(8, int(h * float(frac)))
    y = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2YCrCb)[:, :, 0].astype(np.float32)
    top = float(np.mean(y[:k, :]))
    bot = float(np.mean(y[h - k:, :]))
    if not (np.isfinite(top) and np.isfinite(bot)):
        return False
    return bot > top * float(ratio_thr)

UPRIGHT_CFG = {
    "max_side": 960,

    "gauss_ksize": 5,
    "canny1": 50,
    "canny2": 150,

    "hough_threshold": 80,
    "min_len_frac": 0.10,
    "max_line_gap": 20,

    "hor_tol_deg": 12.0,
    "ver_tol_deg": 12.0,

    "min_lines": 10,
    "min_group_weight_frac": 0.35,

    "max_abs_rot_deg": 25.0
}

def estimate_upright_rotation_deg(img_bgr: np.ndarray) -> float:
    if img_bgr is None or img_bgr.size == 0:
        return 0.0

    H, W = img_bgr.shape[:2]
    if H < 64 or W < 64:
        return 0.0

    cfg = UPRIGHT_CFG
    max_side = int(cfg["max_side"])

    work = img_bgr
    if max(H, W) > max_side:
        s = max_side / float(max(H, W))
        work = cv2.resize(work, (max(2, int(W * s)), max(2, int(H * s))), interpolation=cv2.INTER_AREA)

    g = cv2.cvtColor(work, cv2.COLOR_BGR2GRAY)
    k = int(cfg["gauss_ksize"])
    if k >= 3 and (k % 2 == 1):
        g = cv2.GaussianBlur(g, (k, k), 0)

    edges = cv2.Canny(g, int(cfg["canny1"]), int(cfg["canny2"]))

    m = max(work.shape[:2])
    min_len = max(8, int(float(cfg["min_len_frac"]) * m))
    lines = cv2.HoughLinesP(
        edges, 1, np.pi / 180.0,
        threshold=int(cfg["hough_threshold"]),
        minLineLength=min_len,
        maxLineGap=int(cfg["max_line_gap"])
    )
    if lines is None:
        return 0.0

    hor_tol = float(cfg["hor_tol_deg"])
    ver_tol = float(cfg["ver_tol_deg"])

    sum_all = 0.0

    hor_vals = []
    hor_w = []

    ver_vals = []
    ver_w = []

    for x1, y1, x2, y2 in lines.reshape(-1, 4):
        dx = float(x2 - x1)
        dy = float(y2 - y1)
        L = math.hypot(dx, dy)
        if L < 1.0:
            continue

        ang = math.degrees(math.atan2(dy, dx))
        while ang >= 90.0:
            ang -= 180.0
        while ang < -90.0:
            ang += 180.0

        sum_all += L

        if abs(ang) <= hor_tol:
            hor_vals.append(float(ang))
            hor_w.append(float(L))
            continue

        if abs(abs(ang) - 90.0) <= ver_tol:
            dev = (ang - 90.0) if ang > 0.0 else (ang + 90.0)
            ver_vals.append(float(dev))
            ver_w.append(float(L))
            continue

    if sum_all <= 1e-6:
        return 0.0

    def _wmean(vals, ws):
        sw = float(np.sum(ws))
        if sw <= 1e-6:
            return None
        return float(np.sum(np.array(vals, dtype=np.float32) * np.array(ws, dtype=np.float32)) / sw)

    wh = float(np.sum(hor_w)) if len(hor_w) else 0.0
    wv = float(np.sum(ver_w)) if len(ver_w) else 0.0

    min_lines = int(cfg["min_lines"])
    min_frac = float(cfg["min_group_weight_frac"])

    use_group = None
    if wh >= wv:
        if len(hor_vals) >= min_lines and (wh / sum_all) >= min_frac:
            use_group = "hor"
    else:
        if len(ver_vals) >= min_lines and (wv / sum_all) >= min_frac:
            use_group = "ver"

    if use_group is None:
        return 0.0

    if use_group == "hor":
        mean_dev = _wmean(hor_vals, hor_w)
        if mean_dev is None:
            return 0.0
        rot = -mean_dev
    else:
        mean_dev = _wmean(ver_vals, ver_w)
        if mean_dev is None:
            return 0.0
        rot = -mean_dev

    rot = float(rot)
    if abs(rot) > float(cfg["max_abs_rot_deg"]):
        return 0.0

    if abs(rot) < 0.2:
        return 0.0

    return rot


def canonicalize_orientation(img_bgr: np.ndarray):
    """
    Выравнивание изображения ОДИН РАЗ (без перебора 0/90/180/270 и без повторных YOLO):
    1) оценка наклона по линиям (Hough)
    2) поворот без обрезки (_rotate_bound)
    3) опционально +180°, если кадр “похоже” вверх ногами (простая эвристика)

    Возвращает:
      img_work: выровненный кадр
      info: dict(angle_deg, M) где M — матрица base->work (2x3)
    """
    if img_bgr is None:
        return None, {"angle_deg": 0.0, "M": np.array([[1, 0, 0], [0, 1, 0]], dtype=np.float32)}

    rot1 = estimate_upright_rotation_deg(img_bgr)
    img1, M1, _ = _rotate_bound(img_bgr, rot1)

    M_total = M1
    rot_total = float(rot1)

    if _looks_upside_down(img1):
        img2, M2, _ = _rotate_bound(img1, 180.0)
        M_total = _affine_compose(M2, M_total)
        img1 = img2
        rot_total = rot_total + 180.0
        rot_total = ((rot_total + 180.0) % 360.0) - 180.0

    return img1, {"angle_deg": float(rot_total), "M": M_total}

# идея: 1 машина = 1 бокс
def _containment_suppression(boxes, contain_thr=0.92, conf_margin=0.02):
    """
    Удаляет бокс B, если он почти полностью внутри A и A не слабее по conf.
    contain_thr: доля площади B, покрытая пересечением с A.
    """
    if not boxes:
        return []

    # сортировка по уверенности убыв.
    bxs = sorted(boxes, key=lambda x: x[4], reverse=True)
    keep = []
    for b in bxs:
        x1,y1,x2,y2,cb = b
        area_b = max(0, x2-x1) * max(0, y2-y1)
        if area_b <= 0:
            continue

        drop = False
        for a in keep:
            ax1,ay1,ax2,ay2,ca = a
            ix1, iy1 = max(x1,ax1), max(y1,ay1)
            ix2, iy2 = min(x2,ax2), min(y2,ay2)
            iw, ih = max(0, ix2-ix1), max(0, iy2-iy1)
            inter = iw*ih
            if inter <= 0:
                continue

            cover = inter / (area_b + 1e-9)
            if cover >= contain_thr and ca + conf_margin >= cb:
                drop = True
                break

        if not drop:
            keep.append(b)
    return keep
def _box_area(b):
    return max(0, int(b[2]) - int(b[0])) * max(0, int(b[3]) - int(b[1]))

def _box_center(b):
    return (0.5 * (float(b[0]) + float(b[2])), 0.5 * (float(b[1]) + float(b[3])))

def _box_min_side(b):
    return float(min(max(0, int(b[2]) - int(b[0])), max(0, int(b[3]) - int(b[1]))))

def _containment_cover(a, b):
    """
    Доля площади b, покрытая пересечением с a.
    Если a почти содержит b -> значение близко к 1.
    """
    ax1, ay1, ax2, ay2 = map(float, a[:4])
    bx1, by1, bx2, by2 = map(float, b[:4])

    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    iw, ih = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
    inter = iw * ih
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    if area_b <= 1e-9:
        return 0.0
    return float(inter / area_b)

def _pick_better_box(a, b, conf_margin=0.03):
    """
    Выбор "лучшего" бокса среди двух дублей.
    Если conf почти равны -> берём меньшую площадь (обычно точнее).
    """
    ca = float(a[4]); cb = float(b[4])
    if ca > cb + conf_margin:
        return a
    if cb > ca + conf_margin:
        return b
    return a if _box_area(a) <= _box_area(b) else b

def _drop_big_if_contains_small(boxes, contain_thr=0.92, conf_margin=0.03, area_ratio=1.6):
    """
    Удаляет БОЛЬШОЙ бокс, если он почти содержит маленький,
    и маленький не хуже по conf (или большой сильно больше по площади).
    Это убирает типичную ситуацию: один объект + огромный "фоновой" дубль.
    """
    if not boxes:
        return []
    bxs = sorted(boxes, key=lambda b: _box_area(b))  # от меньших к большим
    alive = [True] * len(bxs)

    for i in range(len(bxs)):
        if not alive[i]:
            continue
        small = bxs[i]
        a_small = _box_area(small)
        if a_small <= 0:
            continue

        for j in range(i + 1, len(bxs)):
            if not alive[j]:
                continue
            big = bxs[j]
            a_big = _box_area(big)
            if a_big <= 0:
                alive[j] = False
                continue

            if _containment_cover(big, small) >= contain_thr:
                # big содержит small
                if (float(small[4]) >= float(big[4]) - conf_margin) or (a_big >= area_ratio * a_small):
                    alive[j] = False

    return [bxs[i] for i in range(len(bxs)) if alive[i]]

def _same_object(a, b, iou_thr=0.20, center_thr=0.45, area_ratio_min=0.35, area_ratio_max=2.8, contain_thr=0.92):
    """
    Считает боксы дублями одного объекта, даже если IoU "не дотягивает"
    из-за поворотов/обратного маппинга.
    """
    ia = float(iou_xyxy(a[:4], b[:4]))
    if ia >= iou_thr:
        return True

    # containment в обе стороны
    if _containment_cover(a, b) >= contain_thr:
        return True
    if _containment_cover(b, a) >= contain_thr:
        return True

    aa = _box_area(a); ab = _box_area(b)
    if aa <= 0 or ab <= 0:
        return False

    r = aa / (ab + 1e-9)
    if r < area_ratio_min or r > area_ratio_max:
        return False

    (cx1, cy1) = _box_center(a)
    (cx2, cy2) = _box_center(b)
    dist = math.hypot(cx1 - cx2, cy1 - cy2)

    scale = max(6.0, 0.5 * (_box_min_side(a) + _box_min_side(b)))
    return dist <= center_thr * scale

def dedup_one_box_per_car(
    boxes,
    nms_thr=0.45,
    contain_thr=0.92,
    conf_margin=0.03,
    center_thr=0.45
):
    """
    Гарантирует "1 машина = 1 бокс" для итогового списка.
    """
    if not boxes:
        return []

    # выкидываем мусор и шум, который не нужен для ориентации/геометрии
    boxes = filter_boxes_geom(boxes)

    # жёсткое IoU-NMS (строже вашего 0.55)
    boxes = nms_union(boxes, thr=float(nms_thr))

    # убираем огромные дубли, которые содержат нормальные маленькие
    boxes = _drop_big_if_contains_small(boxes, contain_thr=contain_thr, conf_margin=conf_margin, area_ratio=1.6)

    # убираем маленькие дубли внутри сильных больших
    boxes = _containment_suppression(boxes, contain_thr=contain_thr, conf_margin=0.02)

    # кластеризация по "похожести" (IoU/центр/containment)
    boxes = sorted(boxes, key=lambda b: float(b[4]), reverse=True)
    kept = []
    for b in boxes:
        merged = False
        for k_idx in range(len(kept)):
            k = kept[k_idx]
            if _same_object(b, k, iou_thr=0.20, center_thr=center_thr, contain_thr=contain_thr):
                kept[k_idx] = _pick_better_box(b, k, conf_margin=conf_margin)
                merged = True
                break
        if not merged:
            kept.append(b)

    # финальный контрольный NMS
    kept = nms_union(kept, thr=max(0.35, float(nms_thr) - 0.05))
    return kept

DET_CFG = {
    "conf": 0.18,
    "iou": 0.55,
    "imgsz": 1984,
    "max_det": 10000,

    # размеры
    # tiling: "off" | "auto" | "always"
    "tiling": "auto",
    "tile": 960,
    "overlap": 0.20,

    # углы
    "k90": (0, 1, 2, 3),          # 0/90/180/270
    "use_upright": True,          # добавить поворот на угол, оцененный по линиям
    "upright_thr_deg": 7.0,       # если |угол| меньше — не добавляем

    # склейка
    "merge_iou": 0.55,
    "do_containment": True,

    # TTA
    "tta": False
}

def _run_yolo_cars_tiled(im_bgr, conf, iou, imgsz, max_det, tta, tile, overlap):
    H, W = im_bgr.shape[:2]
    if H < 2 or W < 2:
        return []

    t = int(tile)
    ov = float(overlap)
    step = max(1, int(round(t * (1.0 - ov))))

    out = []
    y = 0
    while y < H:
        x = 0
        y2 = min(y + t, H)
        while x < W:
            x2 = min(x + t, W)
            crop = im_bgr[y:y2, x:x2]
            boxes = _run_yolo_cars(crop, conf=conf, iou=iou, imgsz=imgsz, max_det=max_det, tta=tta)
            for (x1, y1, x3, y3, c) in boxes:
                out.append((int(x1 + x), int(y1 + y), int(x3 + x), int(y3 + y), float(c)))
            x += step
        y += step
    return out

def _detect_on_image(im_bgr, conf, iou, imgsz, max_det, tta, tiling, tile, overlap):
    H, W = im_bgr.shape[:2]
    if tiling == "always":
        use_tiling = True
    elif tiling == "auto":
        use_tiling = (max(H, W) > int(tile))
    else:
        use_tiling = False

    if use_tiling:
        return _run_yolo_cars_tiled(im_bgr, conf, iou, imgsz, max_det, tta, tile, overlap)
    return _run_yolo_cars(im_bgr, conf, iou, imgsz, max_det, tta=tta)

def detect_all_cars(
    img_bgr,
    conf=None,
    iou=None,
    imgsz=None,
    max_det=None,
    do_containment=None,
    tiling=None,
    tile=None,
    overlap=None,
    k90=None,
    use_upright=None,
    upright_thr_deg=None,
    merge_iou=None,
    tta=None
):
    if img_bgr is None or img_bgr.size == 0:
        return []

    cfg = DET_CFG
    conf = cfg["conf"] if conf is None else float(conf)
    iou = cfg["iou"] if iou is None else float(iou)
    imgsz = cfg["imgsz"] if imgsz is None else int(imgsz)
    max_det = cfg["max_det"] if max_det is None else int(max_det)

    tiling = cfg["tiling"] if tiling is None else str(tiling)
    tile = cfg["tile"] if tile is None else int(tile)
    overlap = cfg["overlap"] if overlap is None else float(overlap)

    k90 = cfg["k90"] if k90 is None else tuple(int(x) for x in k90)
    use_upright = cfg["use_upright"] if use_upright is None else bool(use_upright)
    upright_thr_deg = cfg["upright_thr_deg"] if upright_thr_deg is None else float(upright_thr_deg)

    merge_iou = cfg["merge_iou"] if merge_iou is None else float(merge_iou)
    do_containment = cfg["do_containment"] if do_containment is None else bool(do_containment)
    tta = cfg["tta"] if tta is None else bool(tta)

    H0, W0 = img_bgr.shape[:2]
    all_boxes = []

    # 0/90/180/270
    for k in k90:
        kk = int(k) % 4
        im = rotate_k90_bgr(img_bgr, kk)
        boxes_rot = _detect_on_image(im, conf, iou, imgsz, max_det, tta, tiling, tile, overlap)
        boxes_base = rotate_boxes_k90_back(boxes_rot, W0, H0, kk)
        all_boxes.extend(boxes_base)

    # произвольный угол (оценка по линиям)
    if use_upright:
        rot = float(estimate_upright_rotation_deg(img_bgr))
        if abs(rot) >= upright_thr_deg:
            imr, M, _ = _rotate_bound(img_bgr, rot)
            boxes_r = _detect_on_image(imr, conf, iou, imgsz, max_det, tta, tiling, tile, overlap)
            boxes_base = _map_boxes_from_rotated_to_base(boxes_r, M, W0, H0)
            all_boxes.extend(boxes_base)

    if all_boxes:
        all_boxes = nms_union(all_boxes, thr=merge_iou)
        if do_containment:
            all_boxes = _containment_suppression(all_boxes, contain_thr=0.92, conf_margin=0.02)

    return all_boxes

# Вспомогательные функции для работы с углами и геометрией
def wrap180(a: float) -> float:
    """Нормализует угол в диапазон [-180, 180) градусов."""
    a = ((float(a) + 180.0) % 360.0) - 180.0
    return a

# Функции для работы с линиями
def line_angle(x1, y1, x2, y2):
    """Вычисляет угол линии в радианах, нормализованный в [-π/2, π/2)."""
    ang = math.atan2(y2 - y1, x2 - x1)
    if ang > math.pi / 2:
        ang -= math.pi
    if ang < -math.pi / 2:
        ang += math.pi
    return ang

def line_abcd(l):
    """Преобразует линию (x1, y1, x2, y2) в нормализованное уравнение прямой ax + by + c = 0."""
    x1, y1, x2, y2 = l
    a = y1 - y2
    b = x2 - x1
    c = x1 * y2 - x2 * y1
    s = math.hypot(a, b) + 1e-9
    return a / s, b / s, c / s

def intersect_two(l1, l2):
    """Находит точку пересечения двух линий. Возвращает None, если линии параллельны."""
    a1, b1, c1 = line_abcd(l1)
    a2, b2, c2 = line_abcd(l2)
    det = a1 * b2 - a2 * b1
    if abs(det) < 1e-8:
        return None
    x = (b1 * (-c2) - b2 * (-c1)) / det
    y = (a2 * (-c1) - a1 * (-c2)) / det
    return (float(x), float(y))

def vp_ransac(lines, iters=900):
    """Находит vanishing point (точку схода) используя RANSAC алгоритм."""
    lines = np.asarray(lines, dtype=np.float32)
    n = len(lines)
    if n < 3:
        return None

    # веса по длине отрезка (длинные линии важнее)
    w = np.hypot(lines[:, 2] - lines[:, 0], lines[:, 3] - lines[:, 1]).astype(np.float64)
    w = w / (w.sum() + 1e-12)

    best_err = 1e30
    best = None

    for _ in range(iters):
        # выбираем 2 разных линии с вероятностью ~ длине
        i = int(np.random.choice(n, p=w))
        j = int(np.random.choice(n, p=w))
        if i == j:
            continue

        p = intersect_two(lines[i], lines[j])
        if p is None:
            continue
        x, y = p
        if (not np.isfinite(x)) or (not np.isfinite(y)):
            continue

        # взвешенная L1-ошибка "точка до прямой"
        err = 0.0
        for k in range(n):
            a, b, c = line_abcd(lines[k])
            err += w[k] * abs(a * x + b * y + c)

        if err < best_err:
            best_err = err
            best = (float(x), float(y))

    return best

def assign_axes(groups, bbox, offset_xy):
    """Назначает оси (length, width, height) для групп линий на основе их углов."""
    x1, y1, x2, y2 = bbox
    vps = []
    means = []
    for g in groups:
        vps.append(vanishing_point(g))
        if len(g) == 0:
            means.append(999.0)
        else:
            means.append(np.median([abs(math.degrees(line_angle(*l))) for l in g]))
    idx_height = int(np.argmax(means))
    idx_length = int(np.argmin(means))
    idx_width = list({0, 1, 2} - {idx_height, idx_length})[0] if len(groups) == 3 else None
    vp_len = vps[idx_length]
    vp_wid = vps[idx_width] if idx_width is not None else None
    ox, oy = offset_xy
    if vp_len is not None:
        vp_len = (vp_len[0] + ox, vp_len[1] + oy)
    if vp_wid is not None:
        vp_wid = (vp_wid[0] + ox, vp_wid[1] + oy)
    return vp_len, vp_wid

# Функции для работы с поворотами и матрицами
def project_to_SO3(R):
    """Проецирует матрицу R в SO(3) (специальную ортогональную группу) используя SVD."""
    if R is None or not np.all(np.isfinite(R)):
        return None
    try:
        U, S, Vt = np.linalg.svd(R)
        Rso = U @ Vt
        if np.linalg.det(Rso) < 0:
            Vt[-1, :] *= -1
            Rso = U @ Vt
        return Rso
    except np.linalg.LinAlgError:
        return None

def yaw_guess_from_single_vp(vp, cx, cy, f):
    """Оценивает yaw (рыскание) из одной vanishing point."""
    if vp is None or f is None or (not np.isfinite(f)) or f <= 1e-6:
        return None
    dx = (float(vp[0]) - cx) / f
    dz = 1.0
    yaw = math.degrees(math.atan2(dx, dz))
    yaw = ((yaw + 180) % 360) - 180
    return None if not np.isfinite(yaw) else yaw

# Геометрия: ROI, линии, vanishing points
def make_lsd_roi(img_bgr, bbox, *args, **kwargs):
    return img_bgr, (0, 0)

def inplane_angle(img, bbox):
    """
    Угол "R" (in-plane) объекта внутри bbox.
    Возвращает угол в градусах в диапазоне [-90, 90).

    Исправление проблемы "только 0 или 90":
    - приоритетно используем GrabCut-маску внутри bbox (она отсекает рамку bbox и фон)
    - если GrabCut не дал осмысленного FG, считаем PCA по edge-пикселям, но с обнулением границы,
      чтобы не ловить прямоугольник кропа.
    """
    x1, y1, x2, y2 = map(int, bbox)
    roi = img[y1:y2, x1:x2]
    if roi is None or roi.size == 0:
        return None

    h, w = roi.shape[:2]
    if h < 10 or w < 10:
        return None

    # 1) Попытка через GrabCut (стабильнее)
    binm = grabcut_fg_mask(roi, iters=2, margin=0.08)
    if binm is not None:
        ys, xs = np.where(binm > 0)
    else:
        ys = xs = None

    # 2) Фолбэк: Canny, но без рамки кропа
    if xs is None or len(xs) < 80:
        g = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
        g = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(g)
        g = cv2.GaussianBlur(g, (5, 5), 0)
        e = cv2.Canny(g, 50, 150)

        # убираем границы (иначе minAreaRect/PCA почти всегда даст 0/90 от рамки)
        b = 2
        e[:b, :] = 0
        e[-b:, :] = 0
        e[:, :b] = 0
        e[:, -b:] = 0

        ys, xs = np.where(e > 0)

    if xs is None or len(xs) < 80:
        return None

    # PCA по точкам
    pts = np.column_stack([xs.astype(np.float32), ys.astype(np.float32)])
    pts -= pts.mean(axis=0, keepdims=True)

    cov = (pts.T @ pts) / max(1.0, float(pts.shape[0]))
    evals, evecs = np.linalg.eigh(cov)

    # главная ось — eigenvector с max eigenvalue
    idx = int(np.argmax(evals))
    vx, vy = float(evecs[0, idx]), float(evecs[1, idx])

    ang = math.degrees(math.atan2(vy, vx))  # (-180, 180]
    # нормализация к [-90, 90)
    ang = ((ang + 180.0) % 180.0) - 90.0
    if ang >= 90.0:
        ang -= 180.0
    if ang < -90.0:
        ang += 180.0

    return None if not np.isfinite(ang) else float(ang)


# Геометрия: линии → кластеры → ванишинг-точки
def lsd_lines(roi_bgr, max_side=320):
    if roi_bgr is None or roi_bgr.size == 0:
        return np.empty((0,4), np.float32)

    H, W = roi_bgr.shape[:2]
    scale = 1.0
    work = roi_bgr

    if max(H, W) > max_side:
        scale = max_side / float(max(H, W))
        work = cv2.resize(roi_bgr, (int(W * scale), int(H * scale)), interpolation=cv2.INTER_AREA)

    gray = cv2.cvtColor(work, cv2.COLOR_BGR2GRAY)
    gray = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8)).apply(gray)
    gray = cv2.GaussianBlur(gray, (3,3), 0)

    lsd = cv2.createLineSegmentDetector()
    res = lsd.detect(gray)
    lines = res[0] if res is not None else None
    if lines is None:
        return np.empty((0,4), np.float32)

    L = lines.reshape(-1, 4).astype(np.float32)

    lens = np.hypot(L[:, 2] - L[:, 0], L[:, 3] - L[:, 1])
    min_len = max(6, 0.02 * max(gray.shape[:2]))
    L = L[lens > min_len]

    if scale != 1.0 and len(L) > 0:
        L /= scale

    return L


def grabcut_fg_mask(bgr, iters=2, margin=0.05):
    h, w = bgr.shape[:2]
    if h < 16 or w < 16:
        return None

    mask = np.zeros((h, w), np.uint8)
    bg, fg = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)

    x = int(w * margin)
    y = int(h * margin)
    rw = max(1, int(w * (1 - 2 * margin)))
    rh = max(1, int(h * (1 - 2 * margin)))
    rect = (x, y, rw, rh)

    try:
        cv2.grabCut(bgr, mask, rect, bg, fg, iters, cv2.GC_INIT_WITH_RECT)
        binm = np.where((mask == 1) | (mask == 3), 255, 0).astype(np.uint8)

        # лёгкая чистка
        binm = cv2.morphologyEx(binm, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=1)
        binm = cv2.morphologyEx(binm, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8), iterations=1)

        # если FG почти нет — считаем маску невалидной
        if binm.sum() < 0.02 * h * w * 255:
            return None

        return binm
    except Exception:
        return None


def filter_lines_by_mask(L, binmask):
    if binmask is None:
        return L
    if L is None or len(L) == 0:
        return np.empty((0, 4), np.float32)

    h, w = binmask.shape[:2]
    kept = []
    for x1, y1, x2, y2 in np.asarray(L, dtype=np.float32):
        mx = int(0.5 * (x1 + x2))
        my = int(0.5 * (y1 + y2))
        if 0 <= mx < w and 0 <= my < h and binmask[my, mx] > 0:
            kept.append([x1, y1, x2, y2])

    if not kept:
        return np.empty((0, 4), np.float32)
    return np.asarray(kept, dtype=np.float32)

def cluster_angles(L, k=3):
    if len(L) < 6: return [[],[],[]]
    angs = np.array([line_angle(*l) for l in L], dtype=np.float32).reshape(-1,1)
    centers = np.linspace(-math.pi/2, math.pi/2, k, endpoint=False).reshape(k,1).astype(np.float32)
    for _ in range(20):
        d = (angs - centers.T)**2
        lab = d.argmin(axis=1)
        for i in range(k):
            pts = angs[lab==i]
            if len(pts): centers[i] = np.median(pts)
    return [L[lab==i] for i in range(k)]

def vanishing_point(lines):
    lines = np.asarray(lines, dtype=np.float32)
    if len(lines) < 3:
        return None

    p = vp_ransac(lines, iters=900)
    if p is None:
        return None

    # "медиана пересечений" как стабилизация (если данных достаточно)
    xs, ys = [], []
    n = len(lines)
    for i in range(n):
        for j in range(i + 1, n):
            q = intersect_two(lines[i], lines[j])
            if q is None:
                continue
            if np.isfinite(q[0]) and np.isfinite(q[1]):
                xs.append(q[0])
                ys.append(q[1])

    if len(xs) >= 10:
        return (float(np.median(xs)), float(np.median(ys)))

    return p
def global_vps(img_bgr, max_side=1024):
    H, W = img_bgr.shape[:2]
    if H < 64 or W < 64:
        return None, None, None  # vp1, vp2, f_global

    scale = 1.0
    if max(H, W) > max_side:
        scale = max_side / float(max(H, W))
        small = cv2.resize(img_bgr, (int(W * scale), int(H * scale)), interpolation=cv2.INTER_AREA)
    else:
        small = img_bgr

    h, w = small.shape[:2]
    roi = small  # считаем по всему кадру

    L_raw = lsd_lines(roi)

    binm_roi = None
    if min(roi.shape[:2]) >= 48:
        binm_roi = grabcut_fg_mask(roi, iters=2, margin=0.06)

    L = filter_lines_by_mask(L_raw, binm_roi)

    # защита от "съеденной" маской геометрии: откат к исходным линиям
    if len(L) < max(6, int(0.25 * len(L_raw))):
        L = L_raw

    groups = cluster_angles(L, k=3)



    # VP по группам
    vps = []
    counts = []
    for g in groups:
        g = np.asarray(g, dtype=np.float32)
        counts.append(int(len(g)))
        if len(g) >= 15:
            vps.append(vanishing_point(g))
        else:
            vps.append(None)

    cx, cy = w / 2.0, h / 2.0

    # выбираем пару VP с валидным f^2 и максимальным числом линий
    best = None
    best_score = -1

    idxs = [0, 1, 2]
    for i in range(3):
        for j in range(i + 1, 3):
            vi = vps[i]
            vj = vps[j]
            if vi is None or vj is None:
                continue

            ux1, uy1 = vi[0] - cx, vi[1] - cy
            ux2, uy2 = vj[0] - cx, vj[1] - cy
            f2 = -(ux1 * ux2 + uy1 * uy2)

            # отбрасываем мусорные пары
            if (not np.isfinite(f2)) or (f2 <= 1e-3):
                continue

            f = math.sqrt(float(f2))
            # разумный диапазон фокуса относительно размера (грубая защита от выбросов)
            if not (0.2 * max(w, h) <= f <= 5.0 * max(w, h)):
                continue

            score = counts[i] + counts[j]
            if score > best_score:
                best_score = score
                best = (vi, vj, f)

    if best is None:
        return None, None, None

    (vp1, vp2, f_small) = best

    # масштабируем VP обратно в координаты исходного изображения
    inv = 1.0 / scale
    vp1 = (vp1[0] * inv, vp1[1] * inv)
    vp2 = (vp2[0] * inv, vp2[1] * inv)

    # фокус тоже масштабируется так же (потому что координаты в пикселях)
    f_global = float(f_small * inv)

    return vp1, vp2, f_global

def pose_from_two_vp(vx, vy, cx, cy, f_default, f_override=None):
    if vx is None or vy is None:
        return None

    f = float(f_default)
    if (f_override is not None) and np.isfinite(f_override) and (f_override > 1e-6):
        f = float(f_override)


    Kinv = np.array([[1 / f, 0, -cx / f],
                     [0, 1 / f, -cy / f],
                     [0, 0, 1]], dtype=np.float64)

    r1 = Kinv @ np.array([vx[0], vx[1], 1.0])
    r2 = Kinv @ np.array([vy[0], vy[1], 1.0])

    if (not np.all(np.isfinite(r1))) or (not np.all(np.isfinite(r2))):
        return None

    r1 /= (np.linalg.norm(r1) + 1e-9)
    r2 /= (np.linalg.norm(r2) + 1e-9)

    r3 = np.cross(r1, r2)
    n3 = np.linalg.norm(r3)
    if (not np.isfinite(n3)) or (n3 < 1e-6):
        return None
    r3 /= n3

    R = np.stack([r1, r2, r3], axis=1)
    return project_to_SO3(R)

def euler_zyx_from_R(R):
    if R is None or not np.all(np.isfinite(R)): return None
    yaw   = math.degrees(math.atan2(R[1,0], R[0,0]))
    sy    = math.sqrt(R[0,0]**2 + R[1,0]**2)
    pitch = math.degrees(math.atan2(-R[2,0], sy))
    roll  = math.degrees(math.atan2(R[2,1], R[2,2]))
    if any(map(lambda x: not np.isfinite(x), [yaw,pitch,roll])): return None
    return yaw, pitch, roll

def process_image(img_bgr):
    if img_bgr is None:
        return None, []

    H0, W0 = img_bgr.shape[:2]

    # Выравнивание фото (0/90/180/270) -> вся детекция/геометрия на img_work
    img_work, tf = canonicalize_orientation(img_bgr)
    H, W = img_work.shape[:2]
    r_img_deg = None if tf is None else float(tf.get('angle_deg', 0.0))

    f_default = 0.9 * max(W, H)
    vp_g1, vp_g2, f_g = global_vps(img_work, max_side=1024)
    boxes = detect_all_cars(img_bgr)

    L_frame = lsd_lines(img_work)

    # рисуем и отдаём bbox в системе исходного изображения (как у вас было)
    vis = img_bgr.copy()
    results = []

    for i, (x1, y1, x2, y2, conf) in enumerate(boxes, 1):
        bb_w = _map_bbox_from_base_to_rotated((x1, y1, x2, y2), tf["M"], W, H) if tf is not None else (x1, y1, x2, y2)
        if bb_w is None:
            continue
        x1w, y1w, x2w, y2w = bb_w


        L = L_frame

        # R машины считаем в выровненном кадре -> не зависит от поворота фото
        inpl = inplane_angle(img_work, (x1w, y1w, x2w, y2w))

        groups = cluster_angles(L, k=3)

        vp_len = vp_wid = None
        if len(groups) == 3:
            vps = [vanishing_point(g) if len(g) >= 3 else None for g in groups]
            ang_cent = []
            for g in groups:
                if len(g) == 0:
                    ang_cent.append(None)
                else:
                    ang_cent.append(float(np.median([line_angle(*l) for l in g])))

            def _adiff(a, b):
                if a is None or b is None:
                    return 1e9
                d = a - b
                while d >  math.pi/2: d -= math.pi
                while d < -math.pi/2: d += math.pi
                return abs(d)

            if inpl is not None:
                tgt = math.radians(float(inpl))
                idx_len = int(np.argmin([_adiff(a, tgt) for a in ang_cent]))
                idx_wid = int(np.argmin([_adiff(a, tgt + math.pi/2) for a in ang_cent]))

                if idx_wid == idx_len:
                    absdeg = [999.0 if a is None else abs(math.degrees(a)) for a in ang_cent]
                    idx_height = int(np.argmax(absdeg))
                    idx_len = int(np.argmin(absdeg))
                    idx_wid = list({0,1,2} - {idx_height, idx_len})[0]
            else:
                absdeg = [999.0 if a is None else abs(math.degrees(a)) for a in ang_cent]
                idx_height = int(np.argmax(absdeg))
                idx_len = int(np.argmin(absdeg))
                idx_wid = list({0,1,2} - {idx_height, idx_len})[0]

            vp_len = vps[idx_len]
            vp_wid = vps[idx_wid]


        yaw = pitch = roll = None
        pose_src = "none"

        vp1, vp2 = vp_len, vp_wid
        f_use = f_default

        if (vp1 is None or vp2 is None) and (vp_g1 is not None) and (vp_g2 is not None):
            vp1, vp2 = vp_g1, vp_g2
            f_use = f_g if (f_g is not None and np.isfinite(f_g) and f_g > 1e-6) else f_default
            pose_src = "global_flat"
        elif (vp1 is not None) and (vp2 is not None):
            pose_src = "local"

        if (vp1 is not None) and (vp2 is not None):
            Rm = pose_from_two_vp(vp1, vp2, W / 2.0, H / 2.0, f_default, f_override=f_use)
            angs = euler_zyx_from_R(Rm)
            if angs is not None:
                yaw, pitch, roll = angs
                yaw = ((yaw + 180) % 360) - 180
                pitch = ((pitch + 180) % 360) - 180
                roll  = ((roll  + 180) % 360) - 180

                if pose_src == "global_flat":
                    pitch = 0.0
                    roll = 0.0
            else:
                yaw = pitch = roll = None
                pose_src = "none"

        def _vp_pair_ok(v1, v2, cx, cy, W, H):
            ux1, uy1 = v1[0] - cx, v1[1] - cy
            ux2, uy2 = v2[0] - cx, v2[1] - cy
            f2 = -(ux1 * ux2 + uy1 * uy2)
            if (not np.isfinite(f2)) or (f2 <= 1e-3):
                return False
            f = math.sqrt(float(f2))
            m = max(W, H)
            return (0.2 * m <= f <= 5.0 * m)

        cx, cy = W / 2.0, H / 2.0

        if (vp1 is not None) and (vp2 is not None) and _vp_pair_ok(vp1, vp2, cx, cy, W, H):
            pose_src = "local"
        elif (vp_g1 is not None) and (vp_g2 is not None) and _vp_pair_ok(vp_g1, vp_g2, cx, cy, W, H):
            vp1, vp2 = vp_g1, vp_g2
            f_use = f_g if (f_g is not None and np.isfinite(f_g) and f_g > 1e-6) else f_default
            pose_src = "global_flat"

        if (vp1 is not None) and (vp2 is not None):
            Rm = pose_from_two_vp(vp1, vp2, cx, cy, f_use)
            angs = euler_zyx_from_R(Rm)
            if angs is not None:
                yaw, pitch, roll = angs
                yaw = ((yaw + 180) % 360) - 180
                pitch = ((pitch + 180) % 360) - 180
                roll  = ((roll  + 180) % 360) - 180

                if not (np.isfinite(yaw) and np.isfinite(pitch) and np.isfinite(roll)):
                    yaw = pitch = roll = None
                    pose_src = "none"

                if pose_src == "global_flat":
                    pitch = 0.0
                    roll = 0.0

        # Отрисовка на исходном кадре
        cv2.rectangle(vis, (x1, y1), (x2, y2), (0, 255, 0), 2)

        label = f"#{i}"
        if inpl is not None:
            label += f" Rpos={inpl:.1f}"
        label += f" Rimg={r_img_deg}"
        if yaw is not None:
            # Blender Transform -> Rotation (XYZ Euler), градусы
            label += f" RotX={pitch:.1f} RotY={roll:.1f} RotZ={yaw:.1f}"


        cv2.putText(vis, label, (x1, max(0, y1 - 8)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1, cv2.LINE_AA)

        to_rad = math.radians
        sin_yaw, cos_yaw = (math.sin(to_rad(yaw)), math.cos(to_rad(yaw))) if yaw is not None else (None, None)
        sin_pitch, cos_pitch = (math.sin(to_rad(pitch)), math.cos(to_rad(pitch))) if pitch is not None else (None, None)
        sin_roll, cos_roll = (math.sin(to_rad(roll)), math.cos(to_rad(roll))) if roll is not None else (None, None)

        results.append({
            "id": i,
            "bbox": [int(x1), int(y1), int(x2), int(y2)],
            "conf": round(float(conf), 3),

            # Как у тебя было (оставляю совместимость с текущим форматом)
            "X-pos": None if yaw is None else round(float(yaw), 3),
            "Y-pos": None if pitch is None else round(float(pitch), 3),
            "Z-pos": None if roll is None else round(float(roll), 3),

            # Точное положение (позиция) — отдельными полями.
            # ВАЖНО: если у тебя реально есть источник 3D-позиции — подставь его вместо None ниже.
            "Pos-X": None,
            "Pos-Y": None,
            "Pos-Z": None,

            # Твой угол машины в плоскости кадра (как и был)
            "R-pos": None if inpl is None else round(float(inpl), 3),

            # Rotation для Blender (Transform -> Rotation, Mode: XYZ Euler), градусы
            # Принято: RotX=pitch, RotY=roll, RotZ=yaw
            "Rot-X": None if pitch is None else round(float(pitch), 3),
            "Rot-Y": None if roll is None else round(float(roll), 3),
            "Rot-Z": None if yaw is None else round(float(yaw), 3),

            "pose_src": pose_src,
            "sin_yaw": None if sin_yaw is None else round(float(sin_yaw), 6),
            "cos_yaw": None if cos_yaw is None else round(float(cos_yaw), 6),
            "sin_pitch": None if sin_pitch is None else round(float(sin_pitch), 6),
            "cos_pitch": None if cos_pitch is None else round(float(cos_pitch), 6),
            "sin_roll": None if sin_roll is None else round(float(sin_roll), 6),
            "cos_roll": None if cos_roll is None else round(float(cos_roll), 6),

            # Поворот исходного фото (0/90/180/270)
            "R-img": r_img_deg,
        })
    return vis, results

# ПОЧЕМУ ТЫ С РАЗНЫМИ ФОТОГРАФИЯМИ НЕ РАБОТАЕШЬ, А ТОЛЬКО С КОНКРЕТНЫМИ? Почему сканирует 1 машину при 100?


# Глобально: храним последнюю загрузку и декодированные картинки
UPLOADED_BYTES = {}
UPLOADED_IMAGES = {}

def run_pipeline():
    if files is None:
        raise RuntimeError("run_pipeline() доступен только в Google Colab (files.upload). Используйте run().")
    global UPLOADED_BYTES, UPLOADED_IMAGES
    UPLOADED_BYTES = files.upload()
    UPLOADED_IMAGES = {}

    for fn, data in UPLOADED_BYTES.items():
        img = read_image_auto(data)
        if img is None:
            print(f"{fn}: не удалось прочитать файл")
            continue

        UPLOADED_IMAGES[fn] = img  # <- это и будет использовано графиками

        vis, rows = process_image(img)
        if vis is None:
            print(f"{fn}: ошибка обработки")
            continue

        plt.figure(figsize=(80,32))
        plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
        plt.axis('off')
        plt.show()

        df = pd.DataFrame(rows)
        try:
            from google.colab import data_table
            data_table.DataTable(df, include_index=False)
        except Exception:
            pass

        print(json.dumps(rows, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    run_pipeline()


def run(image_path: str, out_dir: str, cfg: dict, device_mode: str = "auto") -> dict:
    """
    Должна вернуть dict в формате ModuleResult:
    {
      "module_id": "...",
      "image_w": int,
      "image_h": int,
      "device_used": "gpu|cpu",
      "warnings": [..],
      "annotated_image_path": "...",
      "cleaned_image_path": "...",
      "artifacts": {...},
      "timings_ms": {...},
      "detections": [ { "bbox_xyxy":[x1,y1,x2,y2], "conf":float, "cls_id":int, "cls_name":str, "meta":{} } ]
    }
    """
    def run(image_path: str, out_dir: str, cfg: dict, device_mode: str = "auto") -> dict:
        global yolo, YOLO_DEVICE_ARG

    t0 = time.time()
    os.makedirs(out_dir, exist_ok=True)

    warnings = []

    nb = (cfg.get("notebooks", {}) or {}).get("rotation_detect", {}) or {}
    model_path = str(nb.get("model_path", "yolo11n.pt"))

    try:
        if getattr(yolo, "_vk_model_path", None) != model_path:
            yolo = YOLO(model_path)
            yolo._vk_model_path = model_path
    except Exception:
        yolo = YOLO(model_path)
        yolo._vk_model_path = model_path

    YOLO_DEVICE_ARG = None
    device_used = "cpu"
    if (device_mode or "auto") != "cpu" and torch is not None:
        try:
            if torch.cuda.is_available():
                gpu_id = int((cfg.get("device", {}) or {}).get("gpu_id", 0))
                YOLO_DEVICE_ARG = str(gpu_id)
                device_used = "gpu"
        except Exception:
            pass
    if (device_mode or "auto") == "gpu" and device_used != "gpu":
        warnings.append("gpu_requested_but_unavailable")

    img = read_image_path(image_path)
    if img is None:
        raise RuntimeError("Не удалось прочитать изображение")

    H, W = img.shape[:2]

    vis, rows = process_image(img)
    if vis is None:
        vis = img.copy()
        rows = []

    annotated_path = os.path.abspath(os.path.join(out_dir, "annotated_cluster_2.jpg"))
    cv2.imwrite(annotated_path, vis)

    dets = []
    for r in (rows or []):
        bb = r.get("bbox", None)
        if not bb or len(bb) != 4:
            continue

        x1, y1, x2, y2 = map(int, bb)
        conf = r.get("conf", 0.0)

        meta = dict(r)
        meta.pop("bbox", None)
        meta.pop("id", None)
        meta.pop("conf", None)

        for k, v in list(meta.items()):
            if isinstance(v, (np.integer,)):
                meta[k] = int(v)
            elif isinstance(v, (np.floating,)):
                meta[k] = float(v)

        dets.append({
            "bbox_xyxy": [x1, y1, x2, y2],
            "conf": float(conf) if conf is not None else 0.0,
            "cls_id": 2,
            "cls_name": "car",
            "meta": meta
        })

    total_ms = int(round((time.time() - t0) * 1000))

    return {
        "module_id": "cluster_2",
        "image_w": int(W),
        "image_h": int(H),
        "device_used": device_used,
        "warnings": warnings,
        "annotated_image_path": annotated_path,
        "cleaned_image_path": "",
        "artifacts": {},
        "timings_ms": {"total": total_ms, "preprocess": 0, "inference": 0, "postprocess": 0},
        "detections": dets
    }